/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.icelabs.netbox.model.BriefL2VPNType;
import dev.icelabs.netbox.model.BriefOwner;
import dev.icelabs.netbox.model.BriefTenant;
import dev.icelabs.netbox.model.L2VPNStatus;
import dev.icelabs.netbox.model.NestedTag;
import dev.icelabs.netbox.model.RouteTarget;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class L2VPN implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Integer id;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private URI url;

  public static final String SERIALIZED_NAME_DISPLAY_URL = "display_url";
  @SerializedName(SERIALIZED_NAME_DISPLAY_URL)
  @javax.annotation.Nonnull
  private URI displayUrl;

  public static final String SERIALIZED_NAME_DISPLAY = "display";
  @SerializedName(SERIALIZED_NAME_DISPLAY)
  @javax.annotation.Nonnull
  private String display;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  @javax.annotation.Nullable
  private Long identifier;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  @javax.annotation.Nonnull
  private String slug;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private BriefL2VPNType type;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private L2VPNStatus status;

  public static final String SERIALIZED_NAME_IMPORT_TARGETS = "import_targets";
  @SerializedName(SERIALIZED_NAME_IMPORT_TARGETS)
  @javax.annotation.Nullable
  private List<RouteTarget> importTargets = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPORT_TARGETS = "export_targets";
  @SerializedName(SERIALIZED_NAME_EXPORT_TARGETS)
  @javax.annotation.Nullable
  private List<RouteTarget> exportTargets = new ArrayList<>();

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private BriefOwner owner;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  @javax.annotation.Nullable
  private String comments;

  public static final String SERIALIZED_NAME_TENANT = "tenant";
  @SerializedName(SERIALIZED_NAME_TENANT)
  @javax.annotation.Nullable
  private BriefTenant tenant;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<NestedTag> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_CUSTOM_FIELDS = "custom_fields";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELDS)
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nullable
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_LAST_UPDATED = "last_updated";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  public L2VPN() {
  }
  /**
   * Constructor with only readonly parameters
   */
  
  public L2VPN(
     Integer id, 
     URI url, 
     URI displayUrl, 
     String display, 
     OffsetDateTime created, 
     OffsetDateTime lastUpdated
  ) {
    this();
    this.id = id;
    this.url = url;
    this.displayUrl = displayUrl;
    this.display = display;
    this.created = created;
    this.lastUpdated = lastUpdated;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull

  public Integer getId() {
    return id;
  }



  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull

  public URI getUrl() {
    return url;
  }



  /**
   * Get displayUrl
   * @return displayUrl
   */
  @javax.annotation.Nonnull

  public URI getDisplayUrl() {
    return displayUrl;
  }



  /**
   * Get display
   * @return display
   */
  @javax.annotation.Nonnull

  public String getDisplay() {
    return display;
  }



  public L2VPN identifier(@javax.annotation.Nullable Long identifier) {
    
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   * @return identifier
   */
  @javax.annotation.Nullable

  public Long getIdentifier() {
    return identifier;
  }


  public void setIdentifier(@javax.annotation.Nullable Long identifier) {
    this.identifier = identifier;
  }

  public L2VPN name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public L2VPN slug(@javax.annotation.Nonnull String slug) {
    
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull

  public String getSlug() {
    return slug;
  }


  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }

  public L2VPN type(@javax.annotation.Nullable BriefL2VPNType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable

  public BriefL2VPNType getType() {
    return type;
  }


  public void setType(@javax.annotation.Nullable BriefL2VPNType type) {
    this.type = type;
  }

  public L2VPN status(@javax.annotation.Nullable L2VPNStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable

  public L2VPNStatus getStatus() {
    return status;
  }


  public void setStatus(@javax.annotation.Nullable L2VPNStatus status) {
    this.status = status;
  }

  public L2VPN importTargets(@javax.annotation.Nullable List<RouteTarget> importTargets) {
    
    this.importTargets = importTargets;
    return this;
  }

  public L2VPN addImportTargetsItem(RouteTarget importTargetsItem) {
    if (this.importTargets == null) {
      this.importTargets = new ArrayList<>();
    }
    this.importTargets.add(importTargetsItem);
    return this;
  }

  /**
   * Get importTargets
   * @return importTargets
   */
  @javax.annotation.Nullable

  public List<RouteTarget> getImportTargets() {
    return importTargets;
  }


  public void setImportTargets(@javax.annotation.Nullable List<RouteTarget> importTargets) {
    this.importTargets = importTargets;
  }

  public L2VPN exportTargets(@javax.annotation.Nullable List<RouteTarget> exportTargets) {
    
    this.exportTargets = exportTargets;
    return this;
  }

  public L2VPN addExportTargetsItem(RouteTarget exportTargetsItem) {
    if (this.exportTargets == null) {
      this.exportTargets = new ArrayList<>();
    }
    this.exportTargets.add(exportTargetsItem);
    return this;
  }

  /**
   * Get exportTargets
   * @return exportTargets
   */
  @javax.annotation.Nullable

  public List<RouteTarget> getExportTargets() {
    return exportTargets;
  }


  public void setExportTargets(@javax.annotation.Nullable List<RouteTarget> exportTargets) {
    this.exportTargets = exportTargets;
  }

  public L2VPN description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public L2VPN owner(@javax.annotation.Nullable BriefOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable

  public BriefOwner getOwner() {
    return owner;
  }


  public void setOwner(@javax.annotation.Nullable BriefOwner owner) {
    this.owner = owner;
  }

  public L2VPN comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable

  public String getComments() {
    return comments;
  }


  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public L2VPN tenant(@javax.annotation.Nullable BriefTenant tenant) {
    
    this.tenant = tenant;
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable

  public BriefTenant getTenant() {
    return tenant;
  }


  public void setTenant(@javax.annotation.Nullable BriefTenant tenant) {
    this.tenant = tenant;
  }

  public L2VPN tags(@javax.annotation.Nullable List<NestedTag> tags) {
    
    this.tags = tags;
    return this;
  }

  public L2VPN addTagsItem(NestedTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable

  public List<NestedTag> getTags() {
    return tags;
  }


  public void setTags(@javax.annotation.Nullable List<NestedTag> tags) {
    this.tags = tags;
  }

  public L2VPN customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public L2VPN putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable

  public OffsetDateTime getCreated() {
    return created;
  }



  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L2VPN L2VPN = (L2VPN) o;
    return Objects.equals(this.id, L2VPN.id) &&
        Objects.equals(this.url, L2VPN.url) &&
        Objects.equals(this.displayUrl, L2VPN.displayUrl) &&
        Objects.equals(this.display, L2VPN.display) &&
        Objects.equals(this.identifier, L2VPN.identifier) &&
        Objects.equals(this.name, L2VPN.name) &&
        Objects.equals(this.slug, L2VPN.slug) &&
        Objects.equals(this.type, L2VPN.type) &&
        Objects.equals(this.status, L2VPN.status) &&
        Objects.equals(this.importTargets, L2VPN.importTargets) &&
        Objects.equals(this.exportTargets, L2VPN.exportTargets) &&
        Objects.equals(this.description, L2VPN.description) &&
        Objects.equals(this.owner, L2VPN.owner) &&
        Objects.equals(this.comments, L2VPN.comments) &&
        Objects.equals(this.tenant, L2VPN.tenant) &&
        Objects.equals(this.tags, L2VPN.tags) &&
        Objects.equals(this.customFields, L2VPN.customFields) &&
        Objects.equals(this.created, L2VPN.created) &&
        Objects.equals(this.lastUpdated, L2VPN.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, displayUrl, display, identifier, name, slug, type, status, importTargets, exportTargets, description, owner, comments, tenant, tags, customFields, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L2VPN {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    displayUrl: ").append(toIndentedString(displayUrl)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    importTargets: ").append(toIndentedString(importTargets)).append("\n");
    sb.append("    exportTargets: ").append(toIndentedString(exportTargets)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `display_url` to the URL query string
    if (getDisplayUrl() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdisplay_url%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDisplayUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `display` to the URL query string
    if (getDisplay() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdisplay%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDisplay()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `identifier` to the URL query string
    if (getIdentifier() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sidentifier%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIdentifier()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `slug` to the URL query string
    if (getSlug() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sslug%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSlug()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(getType().toUrlQueryString(prefix + "type" + suffix));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(getStatus().toUrlQueryString(prefix + "status" + suffix));
    }

    // add `import_targets` to the URL query string
    if (getImportTargets() != null) {
      for (int i = 0; i < getImportTargets().size(); i++) {
        if (getImportTargets().get(i) != null) {
          joiner.add(getImportTargets().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%simport_targets%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `export_targets` to the URL query string
    if (getExportTargets() != null) {
      for (int i = 0; i < getExportTargets().size(); i++) {
        if (getExportTargets().get(i) != null) {
          joiner.add(getExportTargets().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sexport_targets%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(getOwner().toUrlQueryString(prefix + "owner" + suffix));
    }

    // add `comments` to the URL query string
    if (getComments() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scomments%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComments()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `tenant` to the URL query string
    if (getTenant() != null) {
      joiner.add(getTenant().toUrlQueryString(prefix + "tenant" + suffix));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        if (getTags().get(i) != null) {
          joiner.add(getTags().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stags%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `custom_fields` to the URL query string
    if (getCustomFields() != null) {
      for (String _key : getCustomFields().keySet()) {
        try {
          joiner.add(String.format(java.util.Locale.ROOT, "%scustom_fields%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
              getCustomFields().get(_key), URLEncoder.encode(String.valueOf(getCustomFields().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `last_updated` to the URL query string
    if (getLastUpdated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%slast_updated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastUpdated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

  public static class Builder {

    private L2VPN instance;

    public Builder() {
      this(new L2VPN());
    }

    protected Builder(L2VPN instance) {
      this.instance = instance;
    }

    public L2VPN.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public L2VPN.Builder url(URI url) {
      this.instance.url = url;
      return this;
    }
    public L2VPN.Builder displayUrl(URI displayUrl) {
      this.instance.displayUrl = displayUrl;
      return this;
    }
    public L2VPN.Builder display(String display) {
      this.instance.display = display;
      return this;
    }
    public L2VPN.Builder identifier(Long identifier) {
      this.instance.identifier = identifier;
      return this;
    }
    public L2VPN.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public L2VPN.Builder slug(String slug) {
      this.instance.slug = slug;
      return this;
    }
    public L2VPN.Builder type(BriefL2VPNType type) {
      this.instance.type = type;
      return this;
    }
    public L2VPN.Builder status(L2VPNStatus status) {
      this.instance.status = status;
      return this;
    }
    public L2VPN.Builder importTargets(List<RouteTarget> importTargets) {
      this.instance.importTargets = importTargets;
      return this;
    }
    public L2VPN.Builder exportTargets(List<RouteTarget> exportTargets) {
      this.instance.exportTargets = exportTargets;
      return this;
    }
    public L2VPN.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public L2VPN.Builder owner(BriefOwner owner) {
      this.instance.owner = owner;
      return this;
    }
    public L2VPN.Builder comments(String comments) {
      this.instance.comments = comments;
      return this;
    }
    public L2VPN.Builder tenant(BriefTenant tenant) {
      this.instance.tenant = tenant;
      return this;
    }
    public L2VPN.Builder tags(List<NestedTag> tags) {
      this.instance.tags = tags;
      return this;
    }
    public L2VPN.Builder customFields(Map<String, Object> customFields) {
      this.instance.customFields = customFields;
      return this;
    }
    public L2VPN.Builder created(OffsetDateTime created) {
      this.instance.created = created;
      return this;
    }
    public L2VPN.Builder lastUpdated(OffsetDateTime lastUpdated) {
      this.instance.lastUpdated = lastUpdated;
      return this;
    }


    /**
    * returns a built L2VPN instance.
    *
    * The builder is not reusable.
    */
    public L2VPN build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static L2VPN.Builder builder() {
    return new L2VPN.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public L2VPN.Builder toBuilder() {
    return new L2VPN.Builder()
      .id(getId())
      .url(getUrl())
      .displayUrl(getDisplayUrl())
      .display(getDisplay())
      .identifier(getIdentifier())
      .name(getName())
      .slug(getSlug())
      .type(getType())
      .status(getStatus())
      .importTargets(getImportTargets())
      .exportTargets(getExportTargets())
      .description(getDescription())
      .owner(getOwner())
      .comments(getComments())
      .tenant(getTenant())
      .tags(getTags())
      .customFields(getCustomFields())
      .created(getCreated())
      .lastUpdated(getLastUpdated());
  }


}

