/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.ASNRangeRequestTenant;
import dev.icelabs.netbox.model.InterfaceRequestUntaggedVlan;
import dev.icelabs.netbox.model.NestedTagRequest;
import dev.icelabs.netbox.model.PatchedWritableWirelessLANRequestGroup;
import dev.icelabs.netbox.model.WritableWirelessLANRequest;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * WirelessWirelessLansCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WirelessWirelessLansCreateRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_SSID = "ssid";
  @SerializedName(SERIALIZED_NAME_SSID)
  @javax.annotation.Nonnull
  private String ssid;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_GROUP = "group";
  @SerializedName(SERIALIZED_NAME_GROUP)
  @javax.annotation.Nullable
  private PatchedWritableWirelessLANRequestGroup group;

  /**
   * * &#x60;active&#x60; - Active * &#x60;reserved&#x60; - Reserved * &#x60;disabled&#x60; - Disabled * &#x60;deprecated&#x60; - Deprecated
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE(String.valueOf("active")),
    
    RESERVED(String.valueOf("reserved")),
    
    DISABLED(String.valueOf("disabled")),
    
    DEPRECATED(String.valueOf("deprecated"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_VLAN = "vlan";
  @SerializedName(SERIALIZED_NAME_VLAN)
  @javax.annotation.Nullable
  private InterfaceRequestUntaggedVlan vlan;

  public static final String SERIALIZED_NAME_SCOPE_TYPE = "scope_type";
  @SerializedName(SERIALIZED_NAME_SCOPE_TYPE)
  @javax.annotation.Nullable
  private String scopeType;

  public static final String SERIALIZED_NAME_SCOPE_ID = "scope_id";
  @SerializedName(SERIALIZED_NAME_SCOPE_ID)
  @javax.annotation.Nullable
  private Integer scopeId;

  public static final String SERIALIZED_NAME_TENANT = "tenant";
  @SerializedName(SERIALIZED_NAME_TENANT)
  @javax.annotation.Nullable
  private ASNRangeRequestTenant tenant;

  /**
   * * &#x60;open&#x60; - Open * &#x60;wep&#x60; - WEP * &#x60;wpa-personal&#x60; - WPA Personal (PSK) * &#x60;wpa-enterprise&#x60; - WPA Enterprise
   */
  @JsonAdapter(AuthTypeEnum.Adapter.class)
  public enum AuthTypeEnum {
    OPEN(String.valueOf("open")),
    
    WEP(String.valueOf("wep")),
    
    WPA_PERSONAL(String.valueOf("wpa-personal")),
    
    WPA_ENTERPRISE(String.valueOf("wpa-enterprise")),
    
    EMPTY(String.valueOf(""));

    private String value;

    AuthTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AuthTypeEnum fromValue(String value) {
      for (AuthTypeEnum b : AuthTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AuthTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AuthTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AuthTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AuthTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AUTH_TYPE = "auth_type";
  @SerializedName(SERIALIZED_NAME_AUTH_TYPE)
  @javax.annotation.Nullable
  private AuthTypeEnum authType;

  /**
   * * &#x60;auto&#x60; - Auto * &#x60;tkip&#x60; - TKIP * &#x60;aes&#x60; - AES
   */
  @JsonAdapter(AuthCipherEnum.Adapter.class)
  public enum AuthCipherEnum {
    AUTO(String.valueOf("auto")),
    
    TKIP(String.valueOf("tkip")),
    
    AES(String.valueOf("aes")),
    
    EMPTY(String.valueOf(""));

    private String value;

    AuthCipherEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AuthCipherEnum fromValue(String value) {
      for (AuthCipherEnum b : AuthCipherEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AuthCipherEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AuthCipherEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AuthCipherEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AuthCipherEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AUTH_CIPHER = "auth_cipher";
  @SerializedName(SERIALIZED_NAME_AUTH_CIPHER)
  @javax.annotation.Nullable
  private AuthCipherEnum authCipher;

  public static final String SERIALIZED_NAME_AUTH_PSK = "auth_psk";
  @SerializedName(SERIALIZED_NAME_AUTH_PSK)
  @javax.annotation.Nullable
  private String authPsk;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private ASNRangeRequestOwner owner;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  @javax.annotation.Nullable
  private String comments;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_CUSTOM_FIELDS = "custom_fields";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELDS)
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public WirelessWirelessLansCreateRequest() {
  }

  public WirelessWirelessLansCreateRequest ssid(@javax.annotation.Nonnull String ssid) {
    
    this.ssid = ssid;
    return this;
  }

  /**
   * Get ssid
   * @return ssid
   */
  @javax.annotation.Nonnull

  public String getSsid() {
    return ssid;
  }


  public void setSsid(@javax.annotation.Nonnull String ssid) {
    this.ssid = ssid;
  }

  public WirelessWirelessLansCreateRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public WirelessWirelessLansCreateRequest group(@javax.annotation.Nullable PatchedWritableWirelessLANRequestGroup group) {
    
    this.group = group;
    return this;
  }

  /**
   * Get group
   * @return group
   */
  @javax.annotation.Nullable

  public PatchedWritableWirelessLANRequestGroup getGroup() {
    return group;
  }


  public void setGroup(@javax.annotation.Nullable PatchedWritableWirelessLANRequestGroup group) {
    this.group = group;
  }

  public WirelessWirelessLansCreateRequest status(@javax.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * * &#x60;active&#x60; - Active * &#x60;reserved&#x60; - Reserved * &#x60;disabled&#x60; - Disabled * &#x60;deprecated&#x60; - Deprecated
   * @return status
   */
  @javax.annotation.Nullable

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public WirelessWirelessLansCreateRequest vlan(@javax.annotation.Nullable InterfaceRequestUntaggedVlan vlan) {
    
    this.vlan = vlan;
    return this;
  }

  /**
   * Get vlan
   * @return vlan
   */
  @javax.annotation.Nullable

  public InterfaceRequestUntaggedVlan getVlan() {
    return vlan;
  }


  public void setVlan(@javax.annotation.Nullable InterfaceRequestUntaggedVlan vlan) {
    this.vlan = vlan;
  }

  public WirelessWirelessLansCreateRequest scopeType(@javax.annotation.Nullable String scopeType) {
    
    this.scopeType = scopeType;
    return this;
  }

  /**
   * Get scopeType
   * @return scopeType
   */
  @javax.annotation.Nullable

  public String getScopeType() {
    return scopeType;
  }


  public void setScopeType(@javax.annotation.Nullable String scopeType) {
    this.scopeType = scopeType;
  }

  public WirelessWirelessLansCreateRequest scopeId(@javax.annotation.Nullable Integer scopeId) {
    
    this.scopeId = scopeId;
    return this;
  }

  /**
   * Get scopeId
   * @return scopeId
   */
  @javax.annotation.Nullable

  public Integer getScopeId() {
    return scopeId;
  }


  public void setScopeId(@javax.annotation.Nullable Integer scopeId) {
    this.scopeId = scopeId;
  }

  public WirelessWirelessLansCreateRequest tenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    
    this.tenant = tenant;
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable

  public ASNRangeRequestTenant getTenant() {
    return tenant;
  }


  public void setTenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    this.tenant = tenant;
  }

  public WirelessWirelessLansCreateRequest authType(@javax.annotation.Nullable AuthTypeEnum authType) {
    
    this.authType = authType;
    return this;
  }

  /**
   * * &#x60;open&#x60; - Open * &#x60;wep&#x60; - WEP * &#x60;wpa-personal&#x60; - WPA Personal (PSK) * &#x60;wpa-enterprise&#x60; - WPA Enterprise
   * @return authType
   */
  @javax.annotation.Nullable

  public AuthTypeEnum getAuthType() {
    return authType;
  }


  public void setAuthType(@javax.annotation.Nullable AuthTypeEnum authType) {
    this.authType = authType;
  }

  public WirelessWirelessLansCreateRequest authCipher(@javax.annotation.Nullable AuthCipherEnum authCipher) {
    
    this.authCipher = authCipher;
    return this;
  }

  /**
   * * &#x60;auto&#x60; - Auto * &#x60;tkip&#x60; - TKIP * &#x60;aes&#x60; - AES
   * @return authCipher
   */
  @javax.annotation.Nullable

  public AuthCipherEnum getAuthCipher() {
    return authCipher;
  }


  public void setAuthCipher(@javax.annotation.Nullable AuthCipherEnum authCipher) {
    this.authCipher = authCipher;
  }

  public WirelessWirelessLansCreateRequest authPsk(@javax.annotation.Nullable String authPsk) {
    
    this.authPsk = authPsk;
    return this;
  }

  /**
   * Get authPsk
   * @return authPsk
   */
  @javax.annotation.Nullable

  public String getAuthPsk() {
    return authPsk;
  }


  public void setAuthPsk(@javax.annotation.Nullable String authPsk) {
    this.authPsk = authPsk;
  }

  public WirelessWirelessLansCreateRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable

  public ASNRangeRequestOwner getOwner() {
    return owner;
  }


  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = owner;
  }

  public WirelessWirelessLansCreateRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable

  public String getComments() {
    return comments;
  }


  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public WirelessWirelessLansCreateRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public WirelessWirelessLansCreateRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public WirelessWirelessLansCreateRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public WirelessWirelessLansCreateRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WirelessWirelessLansCreateRequest wirelessWirelessLansCreateRequest = (WirelessWirelessLansCreateRequest) o;
    return Objects.equals(this.ssid, wirelessWirelessLansCreateRequest.ssid) &&
        Objects.equals(this.description, wirelessWirelessLansCreateRequest.description) &&
        Objects.equals(this.group, wirelessWirelessLansCreateRequest.group) &&
        Objects.equals(this.status, wirelessWirelessLansCreateRequest.status) &&
        Objects.equals(this.vlan, wirelessWirelessLansCreateRequest.vlan) &&
        Objects.equals(this.scopeType, wirelessWirelessLansCreateRequest.scopeType) &&
        Objects.equals(this.scopeId, wirelessWirelessLansCreateRequest.scopeId) &&
        Objects.equals(this.tenant, wirelessWirelessLansCreateRequest.tenant) &&
        Objects.equals(this.authType, wirelessWirelessLansCreateRequest.authType) &&
        Objects.equals(this.authCipher, wirelessWirelessLansCreateRequest.authCipher) &&
        Objects.equals(this.authPsk, wirelessWirelessLansCreateRequest.authPsk) &&
        Objects.equals(this.owner, wirelessWirelessLansCreateRequest.owner) &&
        Objects.equals(this.comments, wirelessWirelessLansCreateRequest.comments) &&
        Objects.equals(this.tags, wirelessWirelessLansCreateRequest.tags) &&
        Objects.equals(this.customFields, wirelessWirelessLansCreateRequest.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ssid, description, group, status, vlan, scopeType, scopeId, tenant, authType, authCipher, authPsk, owner, comments, tags, customFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WirelessWirelessLansCreateRequest {\n");
    sb.append("    ssid: ").append(toIndentedString(ssid)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    vlan: ").append(toIndentedString(vlan)).append("\n");
    sb.append("    scopeType: ").append(toIndentedString(scopeType)).append("\n");
    sb.append("    scopeId: ").append(toIndentedString(scopeId)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    authCipher: ").append(toIndentedString(authCipher)).append("\n");
    sb.append("    authPsk: ").append(toIndentedString(authPsk)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ssid` to the URL query string
    if (getSsid() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sssid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSsid()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `group` to the URL query string
    if (getGroup() != null) {
      joiner.add(getGroup().toUrlQueryString(prefix + "group" + suffix));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vlan` to the URL query string
    if (getVlan() != null) {
      joiner.add(getVlan().toUrlQueryString(prefix + "vlan" + suffix));
    }

    // add `scope_type` to the URL query string
    if (getScopeType() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sscope_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScopeType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `scope_id` to the URL query string
    if (getScopeId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sscope_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScopeId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `tenant` to the URL query string
    if (getTenant() != null) {
      joiner.add(getTenant().toUrlQueryString(prefix + "tenant" + suffix));
    }

    // add `auth_type` to the URL query string
    if (getAuthType() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sauth_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAuthType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `auth_cipher` to the URL query string
    if (getAuthCipher() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sauth_cipher%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAuthCipher()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `auth_psk` to the URL query string
    if (getAuthPsk() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sauth_psk%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAuthPsk()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(getOwner().toUrlQueryString(prefix + "owner" + suffix));
    }

    // add `comments` to the URL query string
    if (getComments() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scomments%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComments()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        if (getTags().get(i) != null) {
          joiner.add(getTags().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stags%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `custom_fields` to the URL query string
    if (getCustomFields() != null) {
      for (String _key : getCustomFields().keySet()) {
        try {
          joiner.add(String.format(java.util.Locale.ROOT, "%scustom_fields%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
              getCustomFields().get(_key), URLEncoder.encode(String.valueOf(getCustomFields().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    return joiner.toString();
  }

  public static class Builder {

    private WirelessWirelessLansCreateRequest instance;

    public Builder() {
      this(new WirelessWirelessLansCreateRequest());
    }

    protected Builder(WirelessWirelessLansCreateRequest instance) {
      this.instance = instance;
    }

    public WirelessWirelessLansCreateRequest.Builder ssid(String ssid) {
      this.instance.ssid = ssid;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder group(PatchedWritableWirelessLANRequestGroup group) {
      this.instance.group = group;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder status(StatusEnum status) {
      this.instance.status = status;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder vlan(InterfaceRequestUntaggedVlan vlan) {
      this.instance.vlan = vlan;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder scopeType(String scopeType) {
      this.instance.scopeType = scopeType;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder scopeId(Integer scopeId) {
      this.instance.scopeId = scopeId;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder tenant(ASNRangeRequestTenant tenant) {
      this.instance.tenant = tenant;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder authType(AuthTypeEnum authType) {
      this.instance.authType = authType;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder authCipher(AuthCipherEnum authCipher) {
      this.instance.authCipher = authCipher;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder authPsk(String authPsk) {
      this.instance.authPsk = authPsk;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder owner(ASNRangeRequestOwner owner) {
      this.instance.owner = owner;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder comments(String comments) {
      this.instance.comments = comments;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder tags(List<NestedTagRequest> tags) {
      this.instance.tags = tags;
      return this;
    }
    public WirelessWirelessLansCreateRequest.Builder customFields(Map<String, Object> customFields) {
      this.instance.customFields = customFields;
      return this;
    }


    /**
    * returns a built WirelessWirelessLansCreateRequest instance.
    *
    * The builder is not reusable.
    */
    public WirelessWirelessLansCreateRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WirelessWirelessLansCreateRequest.Builder builder() {
    return new WirelessWirelessLansCreateRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WirelessWirelessLansCreateRequest.Builder toBuilder() {
    return new WirelessWirelessLansCreateRequest.Builder()
      .ssid(getSsid())
      .description(getDescription())
      .group(getGroup())
      .status(getStatus())
      .vlan(getVlan())
      .scopeType(getScopeType())
      .scopeId(getScopeId())
      .tenant(getTenant())
      .authType(getAuthType())
      .authCipher(getAuthCipher())
      .authPsk(getAuthPsk())
      .owner(getOwner())
      .comments(getComments())
      .tags(getTags())
      .customFields(getCustomFields());
  }


}

