/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.icelabs.netbox.model.BriefInterface;
import dev.icelabs.netbox.model.BriefOwner;
import dev.icelabs.netbox.model.BriefTenant;
import dev.icelabs.netbox.model.CableStatus;
import dev.icelabs.netbox.model.CircuitDistanceUnit;
import dev.icelabs.netbox.model.NestedTag;
import dev.icelabs.netbox.model.WirelessLANAuthCipher;
import dev.icelabs.netbox.model.WirelessLANAuthType;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WirelessLink implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Integer id;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private URI url;

  public static final String SERIALIZED_NAME_DISPLAY_URL = "display_url";
  @SerializedName(SERIALIZED_NAME_DISPLAY_URL)
  @javax.annotation.Nonnull
  private URI displayUrl;

  public static final String SERIALIZED_NAME_DISPLAY = "display";
  @SerializedName(SERIALIZED_NAME_DISPLAY)
  @javax.annotation.Nonnull
  private String display;

  public static final String SERIALIZED_NAME_INTERFACE_A = "interface_a";
  @SerializedName(SERIALIZED_NAME_INTERFACE_A)
  @javax.annotation.Nonnull
  private BriefInterface interfaceA;

  public static final String SERIALIZED_NAME_INTERFACE_B = "interface_b";
  @SerializedName(SERIALIZED_NAME_INTERFACE_B)
  @javax.annotation.Nonnull
  private BriefInterface interfaceB;

  public static final String SERIALIZED_NAME_SSID = "ssid";
  @SerializedName(SERIALIZED_NAME_SSID)
  @javax.annotation.Nullable
  private String ssid;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private CableStatus status;

  public static final String SERIALIZED_NAME_TENANT = "tenant";
  @SerializedName(SERIALIZED_NAME_TENANT)
  @javax.annotation.Nullable
  private BriefTenant tenant;

  public static final String SERIALIZED_NAME_AUTH_TYPE = "auth_type";
  @SerializedName(SERIALIZED_NAME_AUTH_TYPE)
  @javax.annotation.Nullable
  private WirelessLANAuthType authType;

  public static final String SERIALIZED_NAME_AUTH_CIPHER = "auth_cipher";
  @SerializedName(SERIALIZED_NAME_AUTH_CIPHER)
  @javax.annotation.Nullable
  private WirelessLANAuthCipher authCipher;

  public static final String SERIALIZED_NAME_AUTH_PSK = "auth_psk";
  @SerializedName(SERIALIZED_NAME_AUTH_PSK)
  @javax.annotation.Nullable
  private String authPsk;

  public static final String SERIALIZED_NAME_DISTANCE = "distance";
  @SerializedName(SERIALIZED_NAME_DISTANCE)
  @javax.annotation.Nullable
  private Double distance;

  public static final String SERIALIZED_NAME_DISTANCE_UNIT = "distance_unit";
  @SerializedName(SERIALIZED_NAME_DISTANCE_UNIT)
  @javax.annotation.Nullable
  private CircuitDistanceUnit distanceUnit;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private BriefOwner owner;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  @javax.annotation.Nullable
  private String comments;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<NestedTag> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_CUSTOM_FIELDS = "custom_fields";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELDS)
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nullable
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_LAST_UPDATED = "last_updated";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  public WirelessLink() {
  }
  /**
   * Constructor with only readonly parameters
   */
  
  public WirelessLink(
     Integer id, 
     URI url, 
     URI displayUrl, 
     String display, 
     OffsetDateTime created, 
     OffsetDateTime lastUpdated
  ) {
    this();
    this.id = id;
    this.url = url;
    this.displayUrl = displayUrl;
    this.display = display;
    this.created = created;
    this.lastUpdated = lastUpdated;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull

  public Integer getId() {
    return id;
  }



  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull

  public URI getUrl() {
    return url;
  }



  /**
   * Get displayUrl
   * @return displayUrl
   */
  @javax.annotation.Nonnull

  public URI getDisplayUrl() {
    return displayUrl;
  }



  /**
   * Get display
   * @return display
   */
  @javax.annotation.Nonnull

  public String getDisplay() {
    return display;
  }



  public WirelessLink interfaceA(@javax.annotation.Nonnull BriefInterface interfaceA) {
    
    this.interfaceA = interfaceA;
    return this;
  }

  /**
   * Get interfaceA
   * @return interfaceA
   */
  @javax.annotation.Nonnull

  public BriefInterface getInterfaceA() {
    return interfaceA;
  }


  public void setInterfaceA(@javax.annotation.Nonnull BriefInterface interfaceA) {
    this.interfaceA = interfaceA;
  }

  public WirelessLink interfaceB(@javax.annotation.Nonnull BriefInterface interfaceB) {
    
    this.interfaceB = interfaceB;
    return this;
  }

  /**
   * Get interfaceB
   * @return interfaceB
   */
  @javax.annotation.Nonnull

  public BriefInterface getInterfaceB() {
    return interfaceB;
  }


  public void setInterfaceB(@javax.annotation.Nonnull BriefInterface interfaceB) {
    this.interfaceB = interfaceB;
  }

  public WirelessLink ssid(@javax.annotation.Nullable String ssid) {
    
    this.ssid = ssid;
    return this;
  }

  /**
   * Get ssid
   * @return ssid
   */
  @javax.annotation.Nullable

  public String getSsid() {
    return ssid;
  }


  public void setSsid(@javax.annotation.Nullable String ssid) {
    this.ssid = ssid;
  }

  public WirelessLink status(@javax.annotation.Nullable CableStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable

  public CableStatus getStatus() {
    return status;
  }


  public void setStatus(@javax.annotation.Nullable CableStatus status) {
    this.status = status;
  }

  public WirelessLink tenant(@javax.annotation.Nullable BriefTenant tenant) {
    
    this.tenant = tenant;
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable

  public BriefTenant getTenant() {
    return tenant;
  }


  public void setTenant(@javax.annotation.Nullable BriefTenant tenant) {
    this.tenant = tenant;
  }

  public WirelessLink authType(@javax.annotation.Nullable WirelessLANAuthType authType) {
    
    this.authType = authType;
    return this;
  }

  /**
   * Get authType
   * @return authType
   */
  @javax.annotation.Nullable

  public WirelessLANAuthType getAuthType() {
    return authType;
  }


  public void setAuthType(@javax.annotation.Nullable WirelessLANAuthType authType) {
    this.authType = authType;
  }

  public WirelessLink authCipher(@javax.annotation.Nullable WirelessLANAuthCipher authCipher) {
    
    this.authCipher = authCipher;
    return this;
  }

  /**
   * Get authCipher
   * @return authCipher
   */
  @javax.annotation.Nullable

  public WirelessLANAuthCipher getAuthCipher() {
    return authCipher;
  }


  public void setAuthCipher(@javax.annotation.Nullable WirelessLANAuthCipher authCipher) {
    this.authCipher = authCipher;
  }

  public WirelessLink authPsk(@javax.annotation.Nullable String authPsk) {
    
    this.authPsk = authPsk;
    return this;
  }

  /**
   * Get authPsk
   * @return authPsk
   */
  @javax.annotation.Nullable

  public String getAuthPsk() {
    return authPsk;
  }


  public void setAuthPsk(@javax.annotation.Nullable String authPsk) {
    this.authPsk = authPsk;
  }

  public WirelessLink distance(@javax.annotation.Nullable Double distance) {
    
    this.distance = distance;
    return this;
  }

  /**
   * Get distance
   * minimum: -1000000
   * maximum: 1000000
   * @return distance
   */
  @javax.annotation.Nullable

  public Double getDistance() {
    return distance;
  }


  public void setDistance(@javax.annotation.Nullable Double distance) {
    this.distance = distance;
  }

  public WirelessLink distanceUnit(@javax.annotation.Nullable CircuitDistanceUnit distanceUnit) {
    
    this.distanceUnit = distanceUnit;
    return this;
  }

  /**
   * Get distanceUnit
   * @return distanceUnit
   */
  @javax.annotation.Nullable

  public CircuitDistanceUnit getDistanceUnit() {
    return distanceUnit;
  }


  public void setDistanceUnit(@javax.annotation.Nullable CircuitDistanceUnit distanceUnit) {
    this.distanceUnit = distanceUnit;
  }

  public WirelessLink description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public WirelessLink owner(@javax.annotation.Nullable BriefOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable

  public BriefOwner getOwner() {
    return owner;
  }


  public void setOwner(@javax.annotation.Nullable BriefOwner owner) {
    this.owner = owner;
  }

  public WirelessLink comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable

  public String getComments() {
    return comments;
  }


  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public WirelessLink tags(@javax.annotation.Nullable List<NestedTag> tags) {
    
    this.tags = tags;
    return this;
  }

  public WirelessLink addTagsItem(NestedTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable

  public List<NestedTag> getTags() {
    return tags;
  }


  public void setTags(@javax.annotation.Nullable List<NestedTag> tags) {
    this.tags = tags;
  }

  public WirelessLink customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public WirelessLink putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable

  public OffsetDateTime getCreated() {
    return created;
  }



  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WirelessLink wirelessLink = (WirelessLink) o;
    return Objects.equals(this.id, wirelessLink.id) &&
        Objects.equals(this.url, wirelessLink.url) &&
        Objects.equals(this.displayUrl, wirelessLink.displayUrl) &&
        Objects.equals(this.display, wirelessLink.display) &&
        Objects.equals(this.interfaceA, wirelessLink.interfaceA) &&
        Objects.equals(this.interfaceB, wirelessLink.interfaceB) &&
        Objects.equals(this.ssid, wirelessLink.ssid) &&
        Objects.equals(this.status, wirelessLink.status) &&
        Objects.equals(this.tenant, wirelessLink.tenant) &&
        Objects.equals(this.authType, wirelessLink.authType) &&
        Objects.equals(this.authCipher, wirelessLink.authCipher) &&
        Objects.equals(this.authPsk, wirelessLink.authPsk) &&
        Objects.equals(this.distance, wirelessLink.distance) &&
        Objects.equals(this.distanceUnit, wirelessLink.distanceUnit) &&
        Objects.equals(this.description, wirelessLink.description) &&
        Objects.equals(this.owner, wirelessLink.owner) &&
        Objects.equals(this.comments, wirelessLink.comments) &&
        Objects.equals(this.tags, wirelessLink.tags) &&
        Objects.equals(this.customFields, wirelessLink.customFields) &&
        Objects.equals(this.created, wirelessLink.created) &&
        Objects.equals(this.lastUpdated, wirelessLink.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, displayUrl, display, interfaceA, interfaceB, ssid, status, tenant, authType, authCipher, authPsk, distance, distanceUnit, description, owner, comments, tags, customFields, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WirelessLink {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    displayUrl: ").append(toIndentedString(displayUrl)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    interfaceA: ").append(toIndentedString(interfaceA)).append("\n");
    sb.append("    interfaceB: ").append(toIndentedString(interfaceB)).append("\n");
    sb.append("    ssid: ").append(toIndentedString(ssid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    authCipher: ").append(toIndentedString(authCipher)).append("\n");
    sb.append("    authPsk: ").append(toIndentedString(authPsk)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    distanceUnit: ").append(toIndentedString(distanceUnit)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `display_url` to the URL query string
    if (getDisplayUrl() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdisplay_url%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDisplayUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `display` to the URL query string
    if (getDisplay() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdisplay%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDisplay()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `interface_a` to the URL query string
    if (getInterfaceA() != null) {
      joiner.add(getInterfaceA().toUrlQueryString(prefix + "interface_a" + suffix));
    }

    // add `interface_b` to the URL query string
    if (getInterfaceB() != null) {
      joiner.add(getInterfaceB().toUrlQueryString(prefix + "interface_b" + suffix));
    }

    // add `ssid` to the URL query string
    if (getSsid() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sssid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSsid()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(getStatus().toUrlQueryString(prefix + "status" + suffix));
    }

    // add `tenant` to the URL query string
    if (getTenant() != null) {
      joiner.add(getTenant().toUrlQueryString(prefix + "tenant" + suffix));
    }

    // add `auth_type` to the URL query string
    if (getAuthType() != null) {
      joiner.add(getAuthType().toUrlQueryString(prefix + "auth_type" + suffix));
    }

    // add `auth_cipher` to the URL query string
    if (getAuthCipher() != null) {
      joiner.add(getAuthCipher().toUrlQueryString(prefix + "auth_cipher" + suffix));
    }

    // add `auth_psk` to the URL query string
    if (getAuthPsk() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sauth_psk%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAuthPsk()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `distance` to the URL query string
    if (getDistance() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdistance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDistance()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `distance_unit` to the URL query string
    if (getDistanceUnit() != null) {
      joiner.add(getDistanceUnit().toUrlQueryString(prefix + "distance_unit" + suffix));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(getOwner().toUrlQueryString(prefix + "owner" + suffix));
    }

    // add `comments` to the URL query string
    if (getComments() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scomments%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComments()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        if (getTags().get(i) != null) {
          joiner.add(getTags().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stags%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `custom_fields` to the URL query string
    if (getCustomFields() != null) {
      for (String _key : getCustomFields().keySet()) {
        try {
          joiner.add(String.format(java.util.Locale.ROOT, "%scustom_fields%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
              getCustomFields().get(_key), URLEncoder.encode(String.valueOf(getCustomFields().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `last_updated` to the URL query string
    if (getLastUpdated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%slast_updated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastUpdated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

  public static class Builder {

    private WirelessLink instance;

    public Builder() {
      this(new WirelessLink());
    }

    protected Builder(WirelessLink instance) {
      this.instance = instance;
    }

    public WirelessLink.Builder id(Integer id) {
      this.instance.id = id;
      return this;
    }
    public WirelessLink.Builder url(URI url) {
      this.instance.url = url;
      return this;
    }
    public WirelessLink.Builder displayUrl(URI displayUrl) {
      this.instance.displayUrl = displayUrl;
      return this;
    }
    public WirelessLink.Builder display(String display) {
      this.instance.display = display;
      return this;
    }
    public WirelessLink.Builder interfaceA(BriefInterface interfaceA) {
      this.instance.interfaceA = interfaceA;
      return this;
    }
    public WirelessLink.Builder interfaceB(BriefInterface interfaceB) {
      this.instance.interfaceB = interfaceB;
      return this;
    }
    public WirelessLink.Builder ssid(String ssid) {
      this.instance.ssid = ssid;
      return this;
    }
    public WirelessLink.Builder status(CableStatus status) {
      this.instance.status = status;
      return this;
    }
    public WirelessLink.Builder tenant(BriefTenant tenant) {
      this.instance.tenant = tenant;
      return this;
    }
    public WirelessLink.Builder authType(WirelessLANAuthType authType) {
      this.instance.authType = authType;
      return this;
    }
    public WirelessLink.Builder authCipher(WirelessLANAuthCipher authCipher) {
      this.instance.authCipher = authCipher;
      return this;
    }
    public WirelessLink.Builder authPsk(String authPsk) {
      this.instance.authPsk = authPsk;
      return this;
    }
    public WirelessLink.Builder distance(Double distance) {
      this.instance.distance = distance;
      return this;
    }
    public WirelessLink.Builder distanceUnit(CircuitDistanceUnit distanceUnit) {
      this.instance.distanceUnit = distanceUnit;
      return this;
    }
    public WirelessLink.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public WirelessLink.Builder owner(BriefOwner owner) {
      this.instance.owner = owner;
      return this;
    }
    public WirelessLink.Builder comments(String comments) {
      this.instance.comments = comments;
      return this;
    }
    public WirelessLink.Builder tags(List<NestedTag> tags) {
      this.instance.tags = tags;
      return this;
    }
    public WirelessLink.Builder customFields(Map<String, Object> customFields) {
      this.instance.customFields = customFields;
      return this;
    }
    public WirelessLink.Builder created(OffsetDateTime created) {
      this.instance.created = created;
      return this;
    }
    public WirelessLink.Builder lastUpdated(OffsetDateTime lastUpdated) {
      this.instance.lastUpdated = lastUpdated;
      return this;
    }


    /**
    * returns a built WirelessLink instance.
    *
    * The builder is not reusable.
    */
    public WirelessLink build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WirelessLink.Builder builder() {
    return new WirelessLink.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WirelessLink.Builder toBuilder() {
    return new WirelessLink.Builder()
      .id(getId())
      .url(getUrl())
      .displayUrl(getDisplayUrl())
      .display(getDisplay())
      .interfaceA(getInterfaceA())
      .interfaceB(getInterfaceB())
      .ssid(getSsid())
      .status(getStatus())
      .tenant(getTenant())
      .authType(getAuthType())
      .authCipher(getAuthCipher())
      .authPsk(getAuthPsk())
      .distance(getDistance())
      .distanceUnit(getDistanceUnit())
      .description(getDescription())
      .owner(getOwner())
      .comments(getComments())
      .tags(getTags())
      .customFields(getCustomFields())
      .created(getCreated())
      .lastUpdated(getLastUpdated());
  }


}

