/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class PatchedTableConfigRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_OBJECT_TYPE = "object_type";
  @SerializedName(SERIALIZED_NAME_OBJECT_TYPE)
  @javax.annotation.Nullable
  private String objectType;

  public static final String SERIALIZED_NAME_TABLE = "table";
  @SerializedName(SERIALIZED_NAME_TABLE)
  @javax.annotation.Nullable
  private String table;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nullable
  private Integer user;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  @javax.annotation.Nullable
  private Integer weight;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_SHARED = "shared";
  @SerializedName(SERIALIZED_NAME_SHARED)
  @javax.annotation.Nullable
  private Boolean shared;

  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  @javax.annotation.Nullable
  private List<String> columns = new ArrayList<>();

  public static final String SERIALIZED_NAME_ORDERING = "ordering";
  @SerializedName(SERIALIZED_NAME_ORDERING)
  @javax.annotation.Nullable
  private List<String> ordering;

  public PatchedTableConfigRequest() {
  }

  public PatchedTableConfigRequest objectType(@javax.annotation.Nullable String objectType) {
    
    this.objectType = objectType;
    return this;
  }

  /**
   * Get objectType
   * @return objectType
   */
  @javax.annotation.Nullable

  public String getObjectType() {
    return objectType;
  }


  public void setObjectType(@javax.annotation.Nullable String objectType) {
    this.objectType = objectType;
  }

  public PatchedTableConfigRequest table(@javax.annotation.Nullable String table) {
    
    this.table = table;
    return this;
  }

  /**
   * Get table
   * @return table
   */
  @javax.annotation.Nullable

  public String getTable() {
    return table;
  }


  public void setTable(@javax.annotation.Nullable String table) {
    this.table = table;
  }

  public PatchedTableConfigRequest name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public PatchedTableConfigRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public PatchedTableConfigRequest user(@javax.annotation.Nullable Integer user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable

  public Integer getUser() {
    return user;
  }


  public void setUser(@javax.annotation.Nullable Integer user) {
    this.user = user;
  }

  public PatchedTableConfigRequest weight(@javax.annotation.Nullable Integer weight) {
    
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * minimum: 0
   * maximum: 32767
   * @return weight
   */
  @javax.annotation.Nullable

  public Integer getWeight() {
    return weight;
  }


  public void setWeight(@javax.annotation.Nullable Integer weight) {
    this.weight = weight;
  }

  public PatchedTableConfigRequest enabled(@javax.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public PatchedTableConfigRequest shared(@javax.annotation.Nullable Boolean shared) {
    
    this.shared = shared;
    return this;
  }

  /**
   * Get shared
   * @return shared
   */
  @javax.annotation.Nullable

  public Boolean getShared() {
    return shared;
  }


  public void setShared(@javax.annotation.Nullable Boolean shared) {
    this.shared = shared;
  }

  public PatchedTableConfigRequest columns(@javax.annotation.Nullable List<String> columns) {
    
    this.columns = columns;
    return this;
  }

  public PatchedTableConfigRequest addColumnsItem(String columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Get columns
   * @return columns
   */
  @javax.annotation.Nullable

  public List<String> getColumns() {
    return columns;
  }


  public void setColumns(@javax.annotation.Nullable List<String> columns) {
    this.columns = columns;
  }

  public PatchedTableConfigRequest ordering(@javax.annotation.Nullable List<String> ordering) {
    
    this.ordering = ordering;
    return this;
  }

  public PatchedTableConfigRequest addOrderingItem(String orderingItem) {
    if (this.ordering == null) {
      this.ordering = new ArrayList<>();
    }
    this.ordering.add(orderingItem);
    return this;
  }

  /**
   * Get ordering
   * @return ordering
   */
  @javax.annotation.Nullable

  public List<String> getOrdering() {
    return ordering;
  }


  public void setOrdering(@javax.annotation.Nullable List<String> ordering) {
    this.ordering = ordering;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchedTableConfigRequest patchedTableConfigRequest = (PatchedTableConfigRequest) o;
    return Objects.equals(this.objectType, patchedTableConfigRequest.objectType) &&
        Objects.equals(this.table, patchedTableConfigRequest.table) &&
        Objects.equals(this.name, patchedTableConfigRequest.name) &&
        Objects.equals(this.description, patchedTableConfigRequest.description) &&
        Objects.equals(this.user, patchedTableConfigRequest.user) &&
        Objects.equals(this.weight, patchedTableConfigRequest.weight) &&
        Objects.equals(this.enabled, patchedTableConfigRequest.enabled) &&
        Objects.equals(this.shared, patchedTableConfigRequest.shared) &&
        Objects.equals(this.columns, patchedTableConfigRequest.columns) &&
        Objects.equals(this.ordering, patchedTableConfigRequest.ordering);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, table, name, description, user, weight, enabled, shared, columns, ordering);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchedTableConfigRequest {\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    table: ").append(toIndentedString(table)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    ordering: ").append(toIndentedString(ordering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `object_type` to the URL query string
    if (getObjectType() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sobject_type%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getObjectType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `table` to the URL query string
    if (getTable() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%stable%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTable()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `user` to the URL query string
    if (getUser() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%suser%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUser()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `weight` to the URL query string
    if (getWeight() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sweight%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWeight()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%senabled%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEnabled()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shared` to the URL query string
    if (getShared() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sshared%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShared()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `columns` to the URL query string
    if (getColumns() != null) {
      for (int i = 0; i < getColumns().size(); i++) {
        try {
          joiner.add(String.format(java.util.Locale.ROOT, "%scolumns%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getColumns().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `ordering` to the URL query string
    if (getOrdering() != null) {
      for (int i = 0; i < getOrdering().size(); i++) {
        try {
          joiner.add(String.format(java.util.Locale.ROOT, "%sordering%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getOrdering().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    return joiner.toString();
  }

  public static class Builder {

    private PatchedTableConfigRequest instance;

    public Builder() {
      this(new PatchedTableConfigRequest());
    }

    protected Builder(PatchedTableConfigRequest instance) {
      this.instance = instance;
    }

    public PatchedTableConfigRequest.Builder objectType(String objectType) {
      this.instance.objectType = objectType;
      return this;
    }
    public PatchedTableConfigRequest.Builder table(String table) {
      this.instance.table = table;
      return this;
    }
    public PatchedTableConfigRequest.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public PatchedTableConfigRequest.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public PatchedTableConfigRequest.Builder user(Integer user) {
      this.instance.user = user;
      return this;
    }
    public PatchedTableConfigRequest.Builder weight(Integer weight) {
      this.instance.weight = weight;
      return this;
    }
    public PatchedTableConfigRequest.Builder enabled(Boolean enabled) {
      this.instance.enabled = enabled;
      return this;
    }
    public PatchedTableConfigRequest.Builder shared(Boolean shared) {
      this.instance.shared = shared;
      return this;
    }
    public PatchedTableConfigRequest.Builder columns(List<String> columns) {
      this.instance.columns = columns;
      return this;
    }
    public PatchedTableConfigRequest.Builder ordering(List<String> ordering) {
      this.instance.ordering = ordering;
      return this;
    }


    /**
    * returns a built PatchedTableConfigRequest instance.
    *
    * The builder is not reusable.
    */
    public PatchedTableConfigRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PatchedTableConfigRequest.Builder builder() {
    return new PatchedTableConfigRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PatchedTableConfigRequest.Builder toBuilder() {
    return new PatchedTableConfigRequest.Builder()
      .objectType(getObjectType())
      .table(getTable())
      .name(getName())
      .description(getDescription())
      .user(getUser())
      .weight(getWeight())
      .enabled(getEnabled())
      .shared(getShared())
      .columns(getColumns())
      .ordering(getOrdering());
  }


}

