/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.TableConfigRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ExtrasTableConfigsCreateRequest
 */
@JsonPropertyOrder({
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_OBJECT_TYPE,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_TABLE,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_NAME,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_DESCRIPTION,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_USER,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_WEIGHT,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_ENABLED,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_SHARED,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_COLUMNS,
  ExtrasTableConfigsCreateRequest.JSON_PROPERTY_ORDERING
})
@JsonTypeName("extras_table_configs_create_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class ExtrasTableConfigsCreateRequest {
  public static final String JSON_PROPERTY_OBJECT_TYPE = "object_type";
  @javax.annotation.Nonnull
  private String objectType;

  public static final String JSON_PROPERTY_TABLE = "table";
  @javax.annotation.Nonnull
  private String table;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nullable
  private Integer user;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  @javax.annotation.Nullable
  private Integer weight;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_SHARED = "shared";
  @javax.annotation.Nullable
  private Boolean shared;

  public static final String JSON_PROPERTY_COLUMNS = "columns";
  @javax.annotation.Nonnull
  private List<String> columns = new ArrayList<>();

  public static final String JSON_PROPERTY_ORDERING = "ordering";
  @javax.annotation.Nullable
  private List<String> ordering;

  public ExtrasTableConfigsCreateRequest() {
  }

  public ExtrasTableConfigsCreateRequest objectType(@javax.annotation.Nonnull String objectType) {
    
    this.objectType = objectType;
    return this;
  }

  /**
   * Get objectType
   * @return objectType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getObjectType() {
    return objectType;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nonnull String objectType) {
    this.objectType = objectType;
  }

  public ExtrasTableConfigsCreateRequest table(@javax.annotation.Nonnull String table) {
    
    this.table = table;
    return this;
  }

  /**
   * Get table
   * @return table
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTable() {
    return table;
  }


  @JsonProperty(value = JSON_PROPERTY_TABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTable(@javax.annotation.Nonnull String table) {
    this.table = table;
  }

  public ExtrasTableConfigsCreateRequest name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public ExtrasTableConfigsCreateRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public ExtrasTableConfigsCreateRequest user(@javax.annotation.Nullable Integer user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUser() {
    return user;
  }


  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@javax.annotation.Nullable Integer user) {
    this.user = user;
  }

  public ExtrasTableConfigsCreateRequest weight(@javax.annotation.Nullable Integer weight) {
    
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * minimum: 0
   * maximum: 32767
   * @return weight
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWeight() {
    return weight;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(@javax.annotation.Nullable Integer weight) {
    this.weight = weight;
  }

  public ExtrasTableConfigsCreateRequest enabled(@javax.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public ExtrasTableConfigsCreateRequest shared(@javax.annotation.Nullable Boolean shared) {
    
    this.shared = shared;
    return this;
  }

  /**
   * Get shared
   * @return shared
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHARED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShared() {
    return shared;
  }


  @JsonProperty(value = JSON_PROPERTY_SHARED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShared(@javax.annotation.Nullable Boolean shared) {
    this.shared = shared;
  }

  public ExtrasTableConfigsCreateRequest columns(@javax.annotation.Nonnull List<String> columns) {
    
    this.columns = columns;
    return this;
  }

  public ExtrasTableConfigsCreateRequest addColumnsItem(String columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Get columns
   * @return columns
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COLUMNS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getColumns() {
    return columns;
  }


  @JsonProperty(value = JSON_PROPERTY_COLUMNS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumns(@javax.annotation.Nonnull List<String> columns) {
    this.columns = columns;
  }

  public ExtrasTableConfigsCreateRequest ordering(@javax.annotation.Nullable List<String> ordering) {
    
    this.ordering = ordering;
    return this;
  }

  public ExtrasTableConfigsCreateRequest addOrderingItem(String orderingItem) {
    if (this.ordering == null) {
      this.ordering = new ArrayList<>();
    }
    this.ordering.add(orderingItem);
    return this;
  }

  /**
   * Get ordering
   * @return ordering
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDERING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getOrdering() {
    return ordering;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDERING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrdering(@javax.annotation.Nullable List<String> ordering) {
    this.ordering = ordering;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtrasTableConfigsCreateRequest extrasTableConfigsCreateRequest = (ExtrasTableConfigsCreateRequest) o;
    return Objects.equals(this.objectType, extrasTableConfigsCreateRequest.objectType) &&
        Objects.equals(this.table, extrasTableConfigsCreateRequest.table) &&
        Objects.equals(this.name, extrasTableConfigsCreateRequest.name) &&
        Objects.equals(this.description, extrasTableConfigsCreateRequest.description) &&
        Objects.equals(this.user, extrasTableConfigsCreateRequest.user) &&
        Objects.equals(this.weight, extrasTableConfigsCreateRequest.weight) &&
        Objects.equals(this.enabled, extrasTableConfigsCreateRequest.enabled) &&
        Objects.equals(this.shared, extrasTableConfigsCreateRequest.shared) &&
        Objects.equals(this.columns, extrasTableConfigsCreateRequest.columns) &&
        Objects.equals(this.ordering, extrasTableConfigsCreateRequest.ordering);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, table, name, description, user, weight, enabled, shared, columns, ordering);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtrasTableConfigsCreateRequest {\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    table: ").append(toIndentedString(table)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    ordering: ").append(toIndentedString(ordering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

