/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.BriefL2VPNTerminationRequestL2vpn;
import dev.icelabs.netbox.model.NestedTagRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Adds support for custom fields and tags.
 */
@JsonPropertyOrder({
  L2VPNTerminationRequest.JSON_PROPERTY_L2VPN,
  L2VPNTerminationRequest.JSON_PROPERTY_ASSIGNED_OBJECT_TYPE,
  L2VPNTerminationRequest.JSON_PROPERTY_ASSIGNED_OBJECT_ID,
  L2VPNTerminationRequest.JSON_PROPERTY_TAGS,
  L2VPNTerminationRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T09:38:16.451149892Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class L2VPNTerminationRequest {
  public static final String JSON_PROPERTY_L2VPN = "l2vpn";
  @javax.annotation.Nonnull
  private BriefL2VPNTerminationRequestL2vpn l2vpn;

  public static final String JSON_PROPERTY_ASSIGNED_OBJECT_TYPE = "assigned_object_type";
  @javax.annotation.Nonnull
  private String assignedObjectType;

  public static final String JSON_PROPERTY_ASSIGNED_OBJECT_ID = "assigned_object_id";
  @javax.annotation.Nonnull
  private Long assignedObjectId;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public L2VPNTerminationRequest() {
  }

  public L2VPNTerminationRequest l2vpn(@javax.annotation.Nonnull BriefL2VPNTerminationRequestL2vpn l2vpn) {
    
    this.l2vpn = l2vpn;
    return this;
  }

  /**
   * Get l2vpn
   * @return l2vpn
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_L2VPN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BriefL2VPNTerminationRequestL2vpn getL2vpn() {
    return l2vpn;
  }


  @JsonProperty(value = JSON_PROPERTY_L2VPN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setL2vpn(@javax.annotation.Nonnull BriefL2VPNTerminationRequestL2vpn l2vpn) {
    this.l2vpn = l2vpn;
  }

  public L2VPNTerminationRequest assignedObjectType(@javax.annotation.Nonnull String assignedObjectType) {
    
    this.assignedObjectType = assignedObjectType;
    return this;
  }

  /**
   * Get assignedObjectType
   * @return assignedObjectType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAssignedObjectType() {
    return assignedObjectType;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssignedObjectType(@javax.annotation.Nonnull String assignedObjectType) {
    this.assignedObjectType = assignedObjectType;
  }

  public L2VPNTerminationRequest assignedObjectId(@javax.annotation.Nonnull Long assignedObjectId) {
    
    this.assignedObjectId = assignedObjectId;
    return this;
  }

  /**
   * Get assignedObjectId
   * minimum: 0
   * maximum: 9223372036854775807
   * @return assignedObjectId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAssignedObjectId() {
    return assignedObjectId;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssignedObjectId(@javax.annotation.Nonnull Long assignedObjectId) {
    this.assignedObjectId = assignedObjectId;
  }

  public L2VPNTerminationRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public L2VPNTerminationRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public L2VPNTerminationRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public L2VPNTerminationRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L2VPNTerminationRequest l2VPNTerminationRequest = (L2VPNTerminationRequest) o;
    return Objects.equals(this.l2vpn, l2VPNTerminationRequest.l2vpn) &&
        Objects.equals(this.assignedObjectType, l2VPNTerminationRequest.assignedObjectType) &&
        Objects.equals(this.assignedObjectId, l2VPNTerminationRequest.assignedObjectId) &&
        Objects.equals(this.tags, l2VPNTerminationRequest.tags) &&
        Objects.equals(this.customFields, l2VPNTerminationRequest.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(l2vpn, assignedObjectType, assignedObjectId, tags, customFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L2VPNTerminationRequest {\n");
    sb.append("    l2vpn: ").append(toIndentedString(l2vpn)).append("\n");
    sb.append("    assignedObjectType: ").append(toIndentedString(assignedObjectType)).append("\n");
    sb.append("    assignedObjectId: ").append(toIndentedString(assignedObjectId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

