/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.BriefOwner;
import dev.icelabs.netbox.model.NestedTag;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  MACAddress.JSON_PROPERTY_ID,
  MACAddress.JSON_PROPERTY_URL,
  MACAddress.JSON_PROPERTY_DISPLAY_URL,
  MACAddress.JSON_PROPERTY_DISPLAY,
  MACAddress.JSON_PROPERTY_MAC_ADDRESS,
  MACAddress.JSON_PROPERTY_ASSIGNED_OBJECT_TYPE,
  MACAddress.JSON_PROPERTY_ASSIGNED_OBJECT_ID,
  MACAddress.JSON_PROPERTY_ASSIGNED_OBJECT,
  MACAddress.JSON_PROPERTY_DESCRIPTION,
  MACAddress.JSON_PROPERTY_OWNER,
  MACAddress.JSON_PROPERTY_COMMENTS,
  MACAddress.JSON_PROPERTY_TAGS,
  MACAddress.JSON_PROPERTY_CUSTOM_FIELDS,
  MACAddress.JSON_PROPERTY_CREATED,
  MACAddress.JSON_PROPERTY_LAST_UPDATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class MACAddress {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nonnull
  private URI url;

  public static final String JSON_PROPERTY_DISPLAY_URL = "display_url";
  @javax.annotation.Nonnull
  private URI displayUrl;

  public static final String JSON_PROPERTY_DISPLAY = "display";
  @javax.annotation.Nonnull
  private String display;

  public static final String JSON_PROPERTY_MAC_ADDRESS = "mac_address";
  @javax.annotation.Nonnull
  private String macAddress;

  public static final String JSON_PROPERTY_ASSIGNED_OBJECT_TYPE = "assigned_object_type";
  @javax.annotation.Nullable
  private String assignedObjectType;

  public static final String JSON_PROPERTY_ASSIGNED_OBJECT_ID = "assigned_object_id";
  @javax.annotation.Nullable
  private Long assignedObjectId;

  public static final String JSON_PROPERTY_ASSIGNED_OBJECT = "assigned_object";
  @javax.annotation.Nullable
  private Object assignedObject = null;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private BriefOwner owner;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTag> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  public MACAddress() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public MACAddress(
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_URL) URI url, 
    @JsonProperty(JSON_PROPERTY_DISPLAY_URL) URI displayUrl, 
    @JsonProperty(JSON_PROPERTY_DISPLAY) String display, 
    @JsonProperty(JSON_PROPERTY_ASSIGNED_OBJECT) Object assignedObject, 
    @JsonProperty(JSON_PROPERTY_CREATED) OffsetDateTime created, 
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED) OffsetDateTime lastUpdated
  ) {
    this();
    this.id = id;
    this.url = url;
    this.displayUrl = displayUrl;
    this.display = display;
    this.assignedObject = assignedObject;
    this.created = created;
    this.lastUpdated = lastUpdated;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }



  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getUrl() {
    return url;
  }



  /**
   * Get displayUrl
   * @return displayUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getDisplayUrl() {
    return displayUrl;
  }



  /**
   * Get display
   * @return display
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDisplay() {
    return display;
  }



  public MACAddress macAddress(@javax.annotation.Nonnull String macAddress) {
    
    this.macAddress = macAddress;
    return this;
  }

  /**
   * Get macAddress
   * @return macAddress
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAC_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMacAddress() {
    return macAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_MAC_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMacAddress(@javax.annotation.Nonnull String macAddress) {
    this.macAddress = macAddress;
  }

  public MACAddress assignedObjectType(@javax.annotation.Nullable String assignedObjectType) {
    
    this.assignedObjectType = assignedObjectType;
    return this;
  }

  /**
   * Get assignedObjectType
   * @return assignedObjectType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssignedObjectType() {
    return assignedObjectType;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssignedObjectType(@javax.annotation.Nullable String assignedObjectType) {
    this.assignedObjectType = assignedObjectType;
  }

  public MACAddress assignedObjectId(@javax.annotation.Nullable Long assignedObjectId) {
    
    this.assignedObjectId = assignedObjectId;
    return this;
  }

  /**
   * Get assignedObjectId
   * minimum: 0
   * maximum: 9223372036854775807
   * @return assignedObjectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAssignedObjectId() {
    return assignedObjectId;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssignedObjectId(@javax.annotation.Nullable Long assignedObjectId) {
    this.assignedObjectId = assignedObjectId;
  }

  /**
   * Get assignedObject
   * @return assignedObject
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSIGNED_OBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getAssignedObject() {
    return assignedObject;
  }



  public MACAddress description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public MACAddress owner(@javax.annotation.Nullable BriefOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BriefOwner getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable BriefOwner owner) {
    this.owner = owner;
  }

  public MACAddress comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public MACAddress tags(@javax.annotation.Nullable List<NestedTag> tags) {
    
    this.tags = tags;
    return this;
  }

  public MACAddress addTagsItem(NestedTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTag> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTag> tags) {
    this.tags = tags;
  }

  public MACAddress customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public MACAddress putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreated() {
    return created;
  }



  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MACAddress maCAddress = (MACAddress) o;
    return Objects.equals(this.id, maCAddress.id) &&
        Objects.equals(this.url, maCAddress.url) &&
        Objects.equals(this.displayUrl, maCAddress.displayUrl) &&
        Objects.equals(this.display, maCAddress.display) &&
        Objects.equals(this.macAddress, maCAddress.macAddress) &&
        Objects.equals(this.assignedObjectType, maCAddress.assignedObjectType) &&
        Objects.equals(this.assignedObjectId, maCAddress.assignedObjectId) &&
        Objects.equals(this.assignedObject, maCAddress.assignedObject) &&
        Objects.equals(this.description, maCAddress.description) &&
        Objects.equals(this.owner, maCAddress.owner) &&
        Objects.equals(this.comments, maCAddress.comments) &&
        Objects.equals(this.tags, maCAddress.tags) &&
        Objects.equals(this.customFields, maCAddress.customFields) &&
        Objects.equals(this.created, maCAddress.created) &&
        Objects.equals(this.lastUpdated, maCAddress.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, displayUrl, display, macAddress, assignedObjectType, assignedObjectId, assignedObject, description, owner, comments, tags, customFields, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MACAddress {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    displayUrl: ").append(toIndentedString(displayUrl)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    macAddress: ").append(toIndentedString(macAddress)).append("\n");
    sb.append("    assignedObjectType: ").append(toIndentedString(assignedObjectType)).append("\n");
    sb.append("    assignedObjectId: ").append(toIndentedString(assignedObjectId)).append("\n");
    sb.append("    assignedObject: ").append(toIndentedString(assignedObject)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

