/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.PowerPort;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PaginatedPowerPortList
 */
@JsonPropertyOrder({
  PaginatedPowerPortList.JSON_PROPERTY_COUNT,
  PaginatedPowerPortList.JSON_PROPERTY_NEXT,
  PaginatedPowerPortList.JSON_PROPERTY_PREVIOUS,
  PaginatedPowerPortList.JSON_PROPERTY_RESULTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class PaginatedPowerPortList {
  public static final String JSON_PROPERTY_COUNT = "count";
  @javax.annotation.Nonnull
  private Integer count;

  public static final String JSON_PROPERTY_NEXT = "next";
  @javax.annotation.Nullable
  private URI next;

  public static final String JSON_PROPERTY_PREVIOUS = "previous";
  @javax.annotation.Nullable
  private URI previous;

  public static final String JSON_PROPERTY_RESULTS = "results";
  @javax.annotation.Nonnull
  private List<PowerPort> results = new ArrayList<>();

  public PaginatedPowerPortList() {
  }

  public PaginatedPowerPortList count(@javax.annotation.Nonnull Integer count) {
    
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCount() {
    return count;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(@javax.annotation.Nonnull Integer count) {
    this.count = count;
  }

  public PaginatedPowerPortList next(@javax.annotation.Nullable URI next) {
    
    this.next = next;
    return this;
  }

  /**
   * Get next
   * @return next
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getNext() {
    return next;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNext(@javax.annotation.Nullable URI next) {
    this.next = next;
  }

  public PaginatedPowerPortList previous(@javax.annotation.Nullable URI previous) {
    
    this.previous = previous;
    return this;
  }

  /**
   * Get previous
   * @return previous
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getPrevious() {
    return previous;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrevious(@javax.annotation.Nullable URI previous) {
    this.previous = previous;
  }

  public PaginatedPowerPortList results(@javax.annotation.Nonnull List<PowerPort> results) {
    
    this.results = results;
    return this;
  }

  public PaginatedPowerPortList addResultsItem(PowerPort resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PowerPort> getResults() {
    return results;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResults(@javax.annotation.Nonnull List<PowerPort> results) {
    this.results = results;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginatedPowerPortList paginatedPowerPortList = (PaginatedPowerPortList) o;
    return Objects.equals(this.count, paginatedPowerPortList.count) &&
        Objects.equals(this.next, paginatedPowerPortList.next) &&
        Objects.equals(this.previous, paginatedPowerPortList.previous) &&
        Objects.equals(this.results, paginatedPowerPortList.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, next, previous, results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginatedPowerPortList {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

