/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.NestedTagRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_NAME,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_DESCRIPTION,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_VERSION,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_MODE,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_PROPOSALS,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_PRESHARED_KEY,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_OWNER,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_COMMENTS,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_TAGS,
  PatchedWritableIKEPolicyRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T09:38:16.451149892Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class PatchedWritableIKEPolicyRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  /**
   * * &#x60;1&#x60; - IKEv1 * &#x60;2&#x60; - IKEv2
   */
  public enum VersionEnum {
    NUMBER_1(Integer.valueOf(1)),
    
    NUMBER_2(Integer.valueOf(2));

    private Integer value;

    VersionEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VersionEnum fromValue(Integer value) {
      for (VersionEnum b : VersionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nullable
  private VersionEnum version;

  /**
   * * &#x60;aggressive&#x60; - Aggressive * &#x60;main&#x60; - Main
   */
  public enum ModeEnum {
    AGGRESSIVE(String.valueOf("aggressive")),
    
    MAIN(String.valueOf("main")),
    
    EMPTY(String.valueOf(""));

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_MODE = "mode";
  @javax.annotation.Nullable
  private JsonNullable<ModeEnum> mode = JsonNullable.<ModeEnum>undefined();

  public static final String JSON_PROPERTY_PROPOSALS = "proposals";
  @javax.annotation.Nullable
  private List<Integer> proposals = new ArrayList<>();

  public static final String JSON_PROPERTY_PRESHARED_KEY = "preshared_key";
  @javax.annotation.Nullable
  private String presharedKey;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private JsonNullable<ASNRangeRequestOwner> owner = JsonNullable.<ASNRangeRequestOwner>undefined();

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public PatchedWritableIKEPolicyRequest() {
  }

  public PatchedWritableIKEPolicyRequest name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public PatchedWritableIKEPolicyRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public PatchedWritableIKEPolicyRequest version(@javax.annotation.Nullable VersionEnum version) {
    
    this.version = version;
    return this;
  }

  /**
   * * &#x60;1&#x60; - IKEv1 * &#x60;2&#x60; - IKEv2
   * minimum: 0
   * maximum: 32767
   * @return version
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VersionEnum getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@javax.annotation.Nullable VersionEnum version) {
    this.version = version;
  }

  public PatchedWritableIKEPolicyRequest mode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = JsonNullable.<ModeEnum>of(mode);
    
    return this;
  }

  /**
   * * &#x60;aggressive&#x60; - Aggressive * &#x60;main&#x60; - Main
   * @return mode
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ModeEnum getMode() {
        return mode.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ModeEnum> getMode_JsonNullable() {
    return mode;
  }
  
  @JsonProperty(JSON_PROPERTY_MODE)
  public void setMode_JsonNullable(JsonNullable<ModeEnum> mode) {
    this.mode = mode;
  }

  public void setMode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = JsonNullable.<ModeEnum>of(mode);
  }

  public PatchedWritableIKEPolicyRequest proposals(@javax.annotation.Nullable List<Integer> proposals) {
    
    this.proposals = proposals;
    return this;
  }

  public PatchedWritableIKEPolicyRequest addProposalsItem(Integer proposalsItem) {
    if (this.proposals == null) {
      this.proposals = new ArrayList<>();
    }
    this.proposals.add(proposalsItem);
    return this;
  }

  /**
   * Get proposals
   * @return proposals
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROPOSALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getProposals() {
    return proposals;
  }


  @JsonProperty(value = JSON_PROPERTY_PROPOSALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProposals(@javax.annotation.Nullable List<Integer> proposals) {
    this.proposals = proposals;
  }

  public PatchedWritableIKEPolicyRequest presharedKey(@javax.annotation.Nullable String presharedKey) {
    
    this.presharedKey = presharedKey;
    return this;
  }

  /**
   * Get presharedKey
   * @return presharedKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRESHARED_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPresharedKey() {
    return presharedKey;
  }


  @JsonProperty(value = JSON_PROPERTY_PRESHARED_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPresharedKey(@javax.annotation.Nullable String presharedKey) {
    this.presharedKey = presharedKey;
  }

  public PatchedWritableIKEPolicyRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = JsonNullable.<ASNRangeRequestOwner>of(owner);
    
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ASNRangeRequestOwner getOwner() {
        return owner.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ASNRangeRequestOwner> getOwner_JsonNullable() {
    return owner;
  }
  
  @JsonProperty(JSON_PROPERTY_OWNER)
  public void setOwner_JsonNullable(JsonNullable<ASNRangeRequestOwner> owner) {
    this.owner = owner;
  }

  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = JsonNullable.<ASNRangeRequestOwner>of(owner);
  }

  public PatchedWritableIKEPolicyRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public PatchedWritableIKEPolicyRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public PatchedWritableIKEPolicyRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public PatchedWritableIKEPolicyRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public PatchedWritableIKEPolicyRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchedWritableIKEPolicyRequest patchedWritableIKEPolicyRequest = (PatchedWritableIKEPolicyRequest) o;
    return Objects.equals(this.name, patchedWritableIKEPolicyRequest.name) &&
        Objects.equals(this.description, patchedWritableIKEPolicyRequest.description) &&
        Objects.equals(this.version, patchedWritableIKEPolicyRequest.version) &&
        equalsNullable(this.mode, patchedWritableIKEPolicyRequest.mode) &&
        Objects.equals(this.proposals, patchedWritableIKEPolicyRequest.proposals) &&
        Objects.equals(this.presharedKey, patchedWritableIKEPolicyRequest.presharedKey) &&
        equalsNullable(this.owner, patchedWritableIKEPolicyRequest.owner) &&
        Objects.equals(this.comments, patchedWritableIKEPolicyRequest.comments) &&
        Objects.equals(this.tags, patchedWritableIKEPolicyRequest.tags) &&
        Objects.equals(this.customFields, patchedWritableIKEPolicyRequest.customFields);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, version, hashCodeNullable(mode), proposals, presharedKey, hashCodeNullable(owner), comments, tags, customFields);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchedWritableIKEPolicyRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    proposals: ").append(toIndentedString(proposals)).append("\n");
    sb.append("    presharedKey: ").append(toIndentedString(presharedKey)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

