/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.ASNRangeRequestTenant;
import dev.icelabs.netbox.model.IPAddressRequestVrf;
import dev.icelabs.netbox.model.IPRangeRequestRole;
import dev.icelabs.netbox.model.InterfaceRequestUntaggedVlan;
import dev.icelabs.netbox.model.NestedTagRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  PatchedWritablePrefixRequest.JSON_PROPERTY_PREFIX,
  PatchedWritablePrefixRequest.JSON_PROPERTY_VRF,
  PatchedWritablePrefixRequest.JSON_PROPERTY_SCOPE_TYPE,
  PatchedWritablePrefixRequest.JSON_PROPERTY_SCOPE_ID,
  PatchedWritablePrefixRequest.JSON_PROPERTY_TENANT,
  PatchedWritablePrefixRequest.JSON_PROPERTY_VLAN,
  PatchedWritablePrefixRequest.JSON_PROPERTY_STATUS,
  PatchedWritablePrefixRequest.JSON_PROPERTY_ROLE,
  PatchedWritablePrefixRequest.JSON_PROPERTY_IS_POOL,
  PatchedWritablePrefixRequest.JSON_PROPERTY_MARK_UTILIZED,
  PatchedWritablePrefixRequest.JSON_PROPERTY_DESCRIPTION,
  PatchedWritablePrefixRequest.JSON_PROPERTY_OWNER,
  PatchedWritablePrefixRequest.JSON_PROPERTY_COMMENTS,
  PatchedWritablePrefixRequest.JSON_PROPERTY_TAGS,
  PatchedWritablePrefixRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T09:38:16.451149892Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class PatchedWritablePrefixRequest {
  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @javax.annotation.Nullable
  private String prefix;

  public static final String JSON_PROPERTY_VRF = "vrf";
  @javax.annotation.Nullable
  private JsonNullable<IPAddressRequestVrf> vrf = JsonNullable.<IPAddressRequestVrf>undefined();

  public static final String JSON_PROPERTY_SCOPE_TYPE = "scope_type";
  @javax.annotation.Nullable
  private JsonNullable<String> scopeType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SCOPE_ID = "scope_id";
  @javax.annotation.Nullable
  private JsonNullable<Integer> scopeId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_TENANT = "tenant";
  @javax.annotation.Nullable
  private JsonNullable<ASNRangeRequestTenant> tenant = JsonNullable.<ASNRangeRequestTenant>undefined();

  public static final String JSON_PROPERTY_VLAN = "vlan";
  @javax.annotation.Nullable
  private JsonNullable<InterfaceRequestUntaggedVlan> vlan = JsonNullable.<InterfaceRequestUntaggedVlan>undefined();

  /**
   * Operational status of this prefix  * &#x60;container&#x60; - Container * &#x60;active&#x60; - Active * &#x60;reserved&#x60; - Reserved * &#x60;deprecated&#x60; - Deprecated
   */
  public enum StatusEnum {
    CONTAINER(String.valueOf("container")),
    
    ACTIVE(String.valueOf("active")),
    
    RESERVED(String.valueOf("reserved")),
    
    DEPRECATED(String.valueOf("deprecated"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private JsonNullable<IPRangeRequestRole> role = JsonNullable.<IPRangeRequestRole>undefined();

  public static final String JSON_PROPERTY_IS_POOL = "is_pool";
  @javax.annotation.Nullable
  private Boolean isPool;

  public static final String JSON_PROPERTY_MARK_UTILIZED = "mark_utilized";
  @javax.annotation.Nullable
  private Boolean markUtilized;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private JsonNullable<ASNRangeRequestOwner> owner = JsonNullable.<ASNRangeRequestOwner>undefined();

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public PatchedWritablePrefixRequest() {
  }

  public PatchedWritablePrefixRequest prefix(@javax.annotation.Nullable String prefix) {
    
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrefix() {
    return prefix;
  }


  @JsonProperty(value = JSON_PROPERTY_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrefix(@javax.annotation.Nullable String prefix) {
    this.prefix = prefix;
  }

  public PatchedWritablePrefixRequest vrf(@javax.annotation.Nullable IPAddressRequestVrf vrf) {
    this.vrf = JsonNullable.<IPAddressRequestVrf>of(vrf);
    
    return this;
  }

  /**
   * Get vrf
   * @return vrf
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public IPAddressRequestVrf getVrf() {
        return vrf.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VRF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<IPAddressRequestVrf> getVrf_JsonNullable() {
    return vrf;
  }
  
  @JsonProperty(JSON_PROPERTY_VRF)
  public void setVrf_JsonNullable(JsonNullable<IPAddressRequestVrf> vrf) {
    this.vrf = vrf;
  }

  public void setVrf(@javax.annotation.Nullable IPAddressRequestVrf vrf) {
    this.vrf = JsonNullable.<IPAddressRequestVrf>of(vrf);
  }

  public PatchedWritablePrefixRequest scopeType(@javax.annotation.Nullable String scopeType) {
    this.scopeType = JsonNullable.<String>of(scopeType);
    
    return this;
  }

  /**
   * Get scopeType
   * @return scopeType
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getScopeType() {
        return scopeType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SCOPE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScopeType_JsonNullable() {
    return scopeType;
  }
  
  @JsonProperty(JSON_PROPERTY_SCOPE_TYPE)
  public void setScopeType_JsonNullable(JsonNullable<String> scopeType) {
    this.scopeType = scopeType;
  }

  public void setScopeType(@javax.annotation.Nullable String scopeType) {
    this.scopeType = JsonNullable.<String>of(scopeType);
  }

  public PatchedWritablePrefixRequest scopeId(@javax.annotation.Nullable Integer scopeId) {
    this.scopeId = JsonNullable.<Integer>of(scopeId);
    
    return this;
  }

  /**
   * Get scopeId
   * @return scopeId
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Integer getScopeId() {
        return scopeId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SCOPE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getScopeId_JsonNullable() {
    return scopeId;
  }
  
  @JsonProperty(JSON_PROPERTY_SCOPE_ID)
  public void setScopeId_JsonNullable(JsonNullable<Integer> scopeId) {
    this.scopeId = scopeId;
  }

  public void setScopeId(@javax.annotation.Nullable Integer scopeId) {
    this.scopeId = JsonNullable.<Integer>of(scopeId);
  }

  public PatchedWritablePrefixRequest tenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    this.tenant = JsonNullable.<ASNRangeRequestTenant>of(tenant);
    
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ASNRangeRequestTenant getTenant() {
        return tenant.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TENANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ASNRangeRequestTenant> getTenant_JsonNullable() {
    return tenant;
  }
  
  @JsonProperty(JSON_PROPERTY_TENANT)
  public void setTenant_JsonNullable(JsonNullable<ASNRangeRequestTenant> tenant) {
    this.tenant = tenant;
  }

  public void setTenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    this.tenant = JsonNullable.<ASNRangeRequestTenant>of(tenant);
  }

  public PatchedWritablePrefixRequest vlan(@javax.annotation.Nullable InterfaceRequestUntaggedVlan vlan) {
    this.vlan = JsonNullable.<InterfaceRequestUntaggedVlan>of(vlan);
    
    return this;
  }

  /**
   * Get vlan
   * @return vlan
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public InterfaceRequestUntaggedVlan getVlan() {
        return vlan.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VLAN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<InterfaceRequestUntaggedVlan> getVlan_JsonNullable() {
    return vlan;
  }
  
  @JsonProperty(JSON_PROPERTY_VLAN)
  public void setVlan_JsonNullable(JsonNullable<InterfaceRequestUntaggedVlan> vlan) {
    this.vlan = vlan;
  }

  public void setVlan(@javax.annotation.Nullable InterfaceRequestUntaggedVlan vlan) {
    this.vlan = JsonNullable.<InterfaceRequestUntaggedVlan>of(vlan);
  }

  public PatchedWritablePrefixRequest status(@javax.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Operational status of this prefix  * &#x60;container&#x60; - Container * &#x60;active&#x60; - Active * &#x60;reserved&#x60; - Reserved * &#x60;deprecated&#x60; - Deprecated
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public PatchedWritablePrefixRequest role(@javax.annotation.Nullable IPRangeRequestRole role) {
    this.role = JsonNullable.<IPRangeRequestRole>of(role);
    
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public IPRangeRequestRole getRole() {
        return role.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<IPRangeRequestRole> getRole_JsonNullable() {
    return role;
  }
  
  @JsonProperty(JSON_PROPERTY_ROLE)
  public void setRole_JsonNullable(JsonNullable<IPRangeRequestRole> role) {
    this.role = role;
  }

  public void setRole(@javax.annotation.Nullable IPRangeRequestRole role) {
    this.role = JsonNullable.<IPRangeRequestRole>of(role);
  }

  public PatchedWritablePrefixRequest isPool(@javax.annotation.Nullable Boolean isPool) {
    
    this.isPool = isPool;
    return this;
  }

  /**
   * All IP addresses within this prefix are considered usable
   * @return isPool
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_POOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPool() {
    return isPool;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_POOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPool(@javax.annotation.Nullable Boolean isPool) {
    this.isPool = isPool;
  }

  public PatchedWritablePrefixRequest markUtilized(@javax.annotation.Nullable Boolean markUtilized) {
    
    this.markUtilized = markUtilized;
    return this;
  }

  /**
   * Treat as fully utilized
   * @return markUtilized
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARK_UTILIZED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMarkUtilized() {
    return markUtilized;
  }


  @JsonProperty(value = JSON_PROPERTY_MARK_UTILIZED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkUtilized(@javax.annotation.Nullable Boolean markUtilized) {
    this.markUtilized = markUtilized;
  }

  public PatchedWritablePrefixRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public PatchedWritablePrefixRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = JsonNullable.<ASNRangeRequestOwner>of(owner);
    
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ASNRangeRequestOwner getOwner() {
        return owner.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ASNRangeRequestOwner> getOwner_JsonNullable() {
    return owner;
  }
  
  @JsonProperty(JSON_PROPERTY_OWNER)
  public void setOwner_JsonNullable(JsonNullable<ASNRangeRequestOwner> owner) {
    this.owner = owner;
  }

  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = JsonNullable.<ASNRangeRequestOwner>of(owner);
  }

  public PatchedWritablePrefixRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public PatchedWritablePrefixRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public PatchedWritablePrefixRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public PatchedWritablePrefixRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public PatchedWritablePrefixRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchedWritablePrefixRequest patchedWritablePrefixRequest = (PatchedWritablePrefixRequest) o;
    return Objects.equals(this.prefix, patchedWritablePrefixRequest.prefix) &&
        equalsNullable(this.vrf, patchedWritablePrefixRequest.vrf) &&
        equalsNullable(this.scopeType, patchedWritablePrefixRequest.scopeType) &&
        equalsNullable(this.scopeId, patchedWritablePrefixRequest.scopeId) &&
        equalsNullable(this.tenant, patchedWritablePrefixRequest.tenant) &&
        equalsNullable(this.vlan, patchedWritablePrefixRequest.vlan) &&
        Objects.equals(this.status, patchedWritablePrefixRequest.status) &&
        equalsNullable(this.role, patchedWritablePrefixRequest.role) &&
        Objects.equals(this.isPool, patchedWritablePrefixRequest.isPool) &&
        Objects.equals(this.markUtilized, patchedWritablePrefixRequest.markUtilized) &&
        Objects.equals(this.description, patchedWritablePrefixRequest.description) &&
        equalsNullable(this.owner, patchedWritablePrefixRequest.owner) &&
        Objects.equals(this.comments, patchedWritablePrefixRequest.comments) &&
        Objects.equals(this.tags, patchedWritablePrefixRequest.tags) &&
        Objects.equals(this.customFields, patchedWritablePrefixRequest.customFields);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefix, hashCodeNullable(vrf), hashCodeNullable(scopeType), hashCodeNullable(scopeId), hashCodeNullable(tenant), hashCodeNullable(vlan), status, hashCodeNullable(role), isPool, markUtilized, description, hashCodeNullable(owner), comments, tags, customFields);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchedWritablePrefixRequest {\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    vrf: ").append(toIndentedString(vrf)).append("\n");
    sb.append("    scopeType: ").append(toIndentedString(scopeType)).append("\n");
    sb.append("    scopeId: ").append(toIndentedString(scopeId)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    vlan: ").append(toIndentedString(vlan)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    isPool: ").append(toIndentedString(isPool)).append("\n");
    sb.append("    markUtilized: ").append(toIndentedString(markUtilized)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

