/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.CircuitTerminationRequestCircuit;
import dev.icelabs.netbox.model.NestedTagRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Adds support for custom fields and tags.
 */
@JsonPropertyOrder({
  PatchedCircuitTerminationRequest.JSON_PROPERTY_CIRCUIT,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_TERM_SIDE,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_TERMINATION_TYPE,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_TERMINATION_ID,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_PORT_SPEED,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_UPSTREAM_SPEED,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_XCONNECT_ID,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_PP_INFO,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_DESCRIPTION,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_MARK_CONNECTED,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_TAGS,
  PatchedCircuitTerminationRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T09:38:16.451149892Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class PatchedCircuitTerminationRequest {
  public static final String JSON_PROPERTY_CIRCUIT = "circuit";
  @javax.annotation.Nullable
  private CircuitTerminationRequestCircuit circuit;

  /**
   * * &#x60;A&#x60; - A * &#x60;Z&#x60; - Z
   */
  public enum TermSideEnum {
    A(String.valueOf("A")),
    
    Z(String.valueOf("Z"));

    private String value;

    TermSideEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TermSideEnum fromValue(String value) {
      for (TermSideEnum b : TermSideEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TERM_SIDE = "term_side";
  @javax.annotation.Nullable
  private TermSideEnum termSide;

  public static final String JSON_PROPERTY_TERMINATION_TYPE = "termination_type";
  @javax.annotation.Nullable
  private JsonNullable<String> terminationType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TERMINATION_ID = "termination_id";
  @javax.annotation.Nullable
  private JsonNullable<Integer> terminationId = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_PORT_SPEED = "port_speed";
  @javax.annotation.Nullable
  private JsonNullable<Integer> portSpeed = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_UPSTREAM_SPEED = "upstream_speed";
  @javax.annotation.Nullable
  private JsonNullable<Integer> upstreamSpeed = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_XCONNECT_ID = "xconnect_id";
  @javax.annotation.Nullable
  private String xconnectId;

  public static final String JSON_PROPERTY_PP_INFO = "pp_info";
  @javax.annotation.Nullable
  private String ppInfo;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_MARK_CONNECTED = "mark_connected";
  @javax.annotation.Nullable
  private Boolean markConnected;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public PatchedCircuitTerminationRequest() {
  }

  public PatchedCircuitTerminationRequest circuit(@javax.annotation.Nullable CircuitTerminationRequestCircuit circuit) {
    
    this.circuit = circuit;
    return this;
  }

  /**
   * Get circuit
   * @return circuit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CIRCUIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CircuitTerminationRequestCircuit getCircuit() {
    return circuit;
  }


  @JsonProperty(value = JSON_PROPERTY_CIRCUIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCircuit(@javax.annotation.Nullable CircuitTerminationRequestCircuit circuit) {
    this.circuit = circuit;
  }

  public PatchedCircuitTerminationRequest termSide(@javax.annotation.Nullable TermSideEnum termSide) {
    
    this.termSide = termSide;
    return this;
  }

  /**
   * * &#x60;A&#x60; - A * &#x60;Z&#x60; - Z
   * @return termSide
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TERM_SIDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TermSideEnum getTermSide() {
    return termSide;
  }


  @JsonProperty(value = JSON_PROPERTY_TERM_SIDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTermSide(@javax.annotation.Nullable TermSideEnum termSide) {
    this.termSide = termSide;
  }

  public PatchedCircuitTerminationRequest terminationType(@javax.annotation.Nullable String terminationType) {
    this.terminationType = JsonNullable.<String>of(terminationType);
    
    return this;
  }

  /**
   * Get terminationType
   * @return terminationType
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getTerminationType() {
        return terminationType.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TERMINATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTerminationType_JsonNullable() {
    return terminationType;
  }
  
  @JsonProperty(JSON_PROPERTY_TERMINATION_TYPE)
  public void setTerminationType_JsonNullable(JsonNullable<String> terminationType) {
    this.terminationType = terminationType;
  }

  public void setTerminationType(@javax.annotation.Nullable String terminationType) {
    this.terminationType = JsonNullable.<String>of(terminationType);
  }

  public PatchedCircuitTerminationRequest terminationId(@javax.annotation.Nullable Integer terminationId) {
    this.terminationId = JsonNullable.<Integer>of(terminationId);
    
    return this;
  }

  /**
   * Get terminationId
   * @return terminationId
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Integer getTerminationId() {
        return terminationId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TERMINATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTerminationId_JsonNullable() {
    return terminationId;
  }
  
  @JsonProperty(JSON_PROPERTY_TERMINATION_ID)
  public void setTerminationId_JsonNullable(JsonNullable<Integer> terminationId) {
    this.terminationId = terminationId;
  }

  public void setTerminationId(@javax.annotation.Nullable Integer terminationId) {
    this.terminationId = JsonNullable.<Integer>of(terminationId);
  }

  public PatchedCircuitTerminationRequest portSpeed(@javax.annotation.Nullable Integer portSpeed) {
    this.portSpeed = JsonNullable.<Integer>of(portSpeed);
    
    return this;
  }

  /**
   * Physical circuit speed
   * minimum: 0
   * maximum: 2147483647
   * @return portSpeed
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Integer getPortSpeed() {
        return portSpeed.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PORT_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getPortSpeed_JsonNullable() {
    return portSpeed;
  }
  
  @JsonProperty(JSON_PROPERTY_PORT_SPEED)
  public void setPortSpeed_JsonNullable(JsonNullable<Integer> portSpeed) {
    this.portSpeed = portSpeed;
  }

  public void setPortSpeed(@javax.annotation.Nullable Integer portSpeed) {
    this.portSpeed = JsonNullable.<Integer>of(portSpeed);
  }

  public PatchedCircuitTerminationRequest upstreamSpeed(@javax.annotation.Nullable Integer upstreamSpeed) {
    this.upstreamSpeed = JsonNullable.<Integer>of(upstreamSpeed);
    
    return this;
  }

  /**
   * Upstream speed, if different from port speed
   * minimum: 0
   * maximum: 2147483647
   * @return upstreamSpeed
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Integer getUpstreamSpeed() {
        return upstreamSpeed.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_UPSTREAM_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getUpstreamSpeed_JsonNullable() {
    return upstreamSpeed;
  }
  
  @JsonProperty(JSON_PROPERTY_UPSTREAM_SPEED)
  public void setUpstreamSpeed_JsonNullable(JsonNullable<Integer> upstreamSpeed) {
    this.upstreamSpeed = upstreamSpeed;
  }

  public void setUpstreamSpeed(@javax.annotation.Nullable Integer upstreamSpeed) {
    this.upstreamSpeed = JsonNullable.<Integer>of(upstreamSpeed);
  }

  public PatchedCircuitTerminationRequest xconnectId(@javax.annotation.Nullable String xconnectId) {
    
    this.xconnectId = xconnectId;
    return this;
  }

  /**
   * ID of the local cross-connect
   * @return xconnectId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_XCONNECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getXconnectId() {
    return xconnectId;
  }


  @JsonProperty(value = JSON_PROPERTY_XCONNECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setXconnectId(@javax.annotation.Nullable String xconnectId) {
    this.xconnectId = xconnectId;
  }

  public PatchedCircuitTerminationRequest ppInfo(@javax.annotation.Nullable String ppInfo) {
    
    this.ppInfo = ppInfo;
    return this;
  }

  /**
   * Patch panel ID and port number(s)
   * @return ppInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PP_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPpInfo() {
    return ppInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_PP_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPpInfo(@javax.annotation.Nullable String ppInfo) {
    this.ppInfo = ppInfo;
  }

  public PatchedCircuitTerminationRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public PatchedCircuitTerminationRequest markConnected(@javax.annotation.Nullable Boolean markConnected) {
    
    this.markConnected = markConnected;
    return this;
  }

  /**
   * Treat as if a cable is connected
   * @return markConnected
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARK_CONNECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMarkConnected() {
    return markConnected;
  }


  @JsonProperty(value = JSON_PROPERTY_MARK_CONNECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkConnected(@javax.annotation.Nullable Boolean markConnected) {
    this.markConnected = markConnected;
  }

  public PatchedCircuitTerminationRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public PatchedCircuitTerminationRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public PatchedCircuitTerminationRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public PatchedCircuitTerminationRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchedCircuitTerminationRequest patchedCircuitTerminationRequest = (PatchedCircuitTerminationRequest) o;
    return Objects.equals(this.circuit, patchedCircuitTerminationRequest.circuit) &&
        Objects.equals(this.termSide, patchedCircuitTerminationRequest.termSide) &&
        equalsNullable(this.terminationType, patchedCircuitTerminationRequest.terminationType) &&
        equalsNullable(this.terminationId, patchedCircuitTerminationRequest.terminationId) &&
        equalsNullable(this.portSpeed, patchedCircuitTerminationRequest.portSpeed) &&
        equalsNullable(this.upstreamSpeed, patchedCircuitTerminationRequest.upstreamSpeed) &&
        Objects.equals(this.xconnectId, patchedCircuitTerminationRequest.xconnectId) &&
        Objects.equals(this.ppInfo, patchedCircuitTerminationRequest.ppInfo) &&
        Objects.equals(this.description, patchedCircuitTerminationRequest.description) &&
        Objects.equals(this.markConnected, patchedCircuitTerminationRequest.markConnected) &&
        Objects.equals(this.tags, patchedCircuitTerminationRequest.tags) &&
        Objects.equals(this.customFields, patchedCircuitTerminationRequest.customFields);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(circuit, termSide, hashCodeNullable(terminationType), hashCodeNullable(terminationId), hashCodeNullable(portSpeed), hashCodeNullable(upstreamSpeed), xconnectId, ppInfo, description, markConnected, tags, customFields);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchedCircuitTerminationRequest {\n");
    sb.append("    circuit: ").append(toIndentedString(circuit)).append("\n");
    sb.append("    termSide: ").append(toIndentedString(termSide)).append("\n");
    sb.append("    terminationType: ").append(toIndentedString(terminationType)).append("\n");
    sb.append("    terminationId: ").append(toIndentedString(terminationId)).append("\n");
    sb.append("    portSpeed: ").append(toIndentedString(portSpeed)).append("\n");
    sb.append("    upstreamSpeed: ").append(toIndentedString(upstreamSpeed)).append("\n");
    sb.append("    xconnectId: ").append(toIndentedString(xconnectId)).append("\n");
    sb.append("    ppInfo: ").append(toIndentedString(ppInfo)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    markConnected: ").append(toIndentedString(markConnected)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

