/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.ASNRangeRequestTenant;
import dev.icelabs.netbox.model.DeviceWithConfigContextRequestRack;
import dev.icelabs.netbox.model.NestedTagRequest;
import dev.icelabs.netbox.model.PatchedWritablePowerFeedRequestPowerPanel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  PowerFeedRequest.JSON_PROPERTY_POWER_PANEL,
  PowerFeedRequest.JSON_PROPERTY_RACK,
  PowerFeedRequest.JSON_PROPERTY_NAME,
  PowerFeedRequest.JSON_PROPERTY_STATUS,
  PowerFeedRequest.JSON_PROPERTY_TYPE,
  PowerFeedRequest.JSON_PROPERTY_SUPPLY,
  PowerFeedRequest.JSON_PROPERTY_PHASE,
  PowerFeedRequest.JSON_PROPERTY_VOLTAGE,
  PowerFeedRequest.JSON_PROPERTY_AMPERAGE,
  PowerFeedRequest.JSON_PROPERTY_MAX_UTILIZATION,
  PowerFeedRequest.JSON_PROPERTY_MARK_CONNECTED,
  PowerFeedRequest.JSON_PROPERTY_DESCRIPTION,
  PowerFeedRequest.JSON_PROPERTY_TENANT,
  PowerFeedRequest.JSON_PROPERTY_OWNER,
  PowerFeedRequest.JSON_PROPERTY_COMMENTS,
  PowerFeedRequest.JSON_PROPERTY_TAGS,
  PowerFeedRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class PowerFeedRequest {
  public static final String JSON_PROPERTY_POWER_PANEL = "power_panel";
  @javax.annotation.Nonnull
  private PatchedWritablePowerFeedRequestPowerPanel powerPanel;

  public static final String JSON_PROPERTY_RACK = "rack";
  @javax.annotation.Nullable
  private DeviceWithConfigContextRequestRack rack;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  /**
   * * &#x60;offline&#x60; - Offline * &#x60;active&#x60; - Active * &#x60;planned&#x60; - Planned * &#x60;failed&#x60; - Failed
   */
  public enum StatusEnum {
    OFFLINE(String.valueOf("offline")),
    
    ACTIVE(String.valueOf("active")),
    
    PLANNED(String.valueOf("planned")),
    
    FAILED(String.valueOf("failed"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  /**
   * * &#x60;primary&#x60; - Primary * &#x60;redundant&#x60; - Redundant
   */
  public enum TypeEnum {
    PRIMARY(String.valueOf("primary")),
    
    REDUNDANT(String.valueOf("redundant"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private TypeEnum type;

  /**
   * * &#x60;ac&#x60; - AC * &#x60;dc&#x60; - DC
   */
  public enum SupplyEnum {
    AC(String.valueOf("ac")),
    
    DC(String.valueOf("dc"));

    private String value;

    SupplyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SupplyEnum fromValue(String value) {
      for (SupplyEnum b : SupplyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SUPPLY = "supply";
  @javax.annotation.Nullable
  private SupplyEnum supply;

  /**
   * * &#x60;single-phase&#x60; - Single phase * &#x60;three-phase&#x60; - Three-phase
   */
  public enum PhaseEnum {
    SINGLE_PHASE(String.valueOf("single-phase")),
    
    THREE_PHASE(String.valueOf("three-phase"));

    private String value;

    PhaseEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PhaseEnum fromValue(String value) {
      for (PhaseEnum b : PhaseEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PHASE = "phase";
  @javax.annotation.Nullable
  private PhaseEnum phase;

  public static final String JSON_PROPERTY_VOLTAGE = "voltage";
  @javax.annotation.Nullable
  private Integer voltage;

  public static final String JSON_PROPERTY_AMPERAGE = "amperage";
  @javax.annotation.Nullable
  private Integer amperage;

  public static final String JSON_PROPERTY_MAX_UTILIZATION = "max_utilization";
  @javax.annotation.Nullable
  private Integer maxUtilization;

  public static final String JSON_PROPERTY_MARK_CONNECTED = "mark_connected";
  @javax.annotation.Nullable
  private Boolean markConnected;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_TENANT = "tenant";
  @javax.annotation.Nullable
  private ASNRangeRequestTenant tenant;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private ASNRangeRequestOwner owner;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public PowerFeedRequest() {
  }

  public PowerFeedRequest powerPanel(@javax.annotation.Nonnull PatchedWritablePowerFeedRequestPowerPanel powerPanel) {
    
    this.powerPanel = powerPanel;
    return this;
  }

  /**
   * Get powerPanel
   * @return powerPanel
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POWER_PANEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PatchedWritablePowerFeedRequestPowerPanel getPowerPanel() {
    return powerPanel;
  }


  @JsonProperty(value = JSON_PROPERTY_POWER_PANEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPowerPanel(@javax.annotation.Nonnull PatchedWritablePowerFeedRequestPowerPanel powerPanel) {
    this.powerPanel = powerPanel;
  }

  public PowerFeedRequest rack(@javax.annotation.Nullable DeviceWithConfigContextRequestRack rack) {
    
    this.rack = rack;
    return this;
  }

  /**
   * Get rack
   * @return rack
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceWithConfigContextRequestRack getRack() {
    return rack;
  }


  @JsonProperty(value = JSON_PROPERTY_RACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRack(@javax.annotation.Nullable DeviceWithConfigContextRequestRack rack) {
    this.rack = rack;
  }

  public PowerFeedRequest name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public PowerFeedRequest status(@javax.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * * &#x60;offline&#x60; - Offline * &#x60;active&#x60; - Active * &#x60;planned&#x60; - Planned * &#x60;failed&#x60; - Failed
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public PowerFeedRequest type(@javax.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * * &#x60;primary&#x60; - Primary * &#x60;redundant&#x60; - Redundant
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public PowerFeedRequest supply(@javax.annotation.Nullable SupplyEnum supply) {
    
    this.supply = supply;
    return this;
  }

  /**
   * * &#x60;ac&#x60; - AC * &#x60;dc&#x60; - DC
   * @return supply
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUPPLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SupplyEnum getSupply() {
    return supply;
  }


  @JsonProperty(value = JSON_PROPERTY_SUPPLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupply(@javax.annotation.Nullable SupplyEnum supply) {
    this.supply = supply;
  }

  public PowerFeedRequest phase(@javax.annotation.Nullable PhaseEnum phase) {
    
    this.phase = phase;
    return this;
  }

  /**
   * * &#x60;single-phase&#x60; - Single phase * &#x60;three-phase&#x60; - Three-phase
   * @return phase
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PhaseEnum getPhase() {
    return phase;
  }


  @JsonProperty(value = JSON_PROPERTY_PHASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhase(@javax.annotation.Nullable PhaseEnum phase) {
    this.phase = phase;
  }

  public PowerFeedRequest voltage(@javax.annotation.Nullable Integer voltage) {
    
    this.voltage = voltage;
    return this;
  }

  /**
   * Get voltage
   * minimum: -32768
   * maximum: 32767
   * @return voltage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VOLTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVoltage() {
    return voltage;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLTAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVoltage(@javax.annotation.Nullable Integer voltage) {
    this.voltage = voltage;
  }

  public PowerFeedRequest amperage(@javax.annotation.Nullable Integer amperage) {
    
    this.amperage = amperage;
    return this;
  }

  /**
   * Get amperage
   * minimum: 1
   * maximum: 32767
   * @return amperage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AMPERAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmperage() {
    return amperage;
  }


  @JsonProperty(value = JSON_PROPERTY_AMPERAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmperage(@javax.annotation.Nullable Integer amperage) {
    this.amperage = amperage;
  }

  public PowerFeedRequest maxUtilization(@javax.annotation.Nullable Integer maxUtilization) {
    
    this.maxUtilization = maxUtilization;
    return this;
  }

  /**
   * Maximum permissible draw (percentage)
   * minimum: 1
   * maximum: 100
   * @return maxUtilization
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_UTILIZATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxUtilization() {
    return maxUtilization;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_UTILIZATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxUtilization(@javax.annotation.Nullable Integer maxUtilization) {
    this.maxUtilization = maxUtilization;
  }

  public PowerFeedRequest markConnected(@javax.annotation.Nullable Boolean markConnected) {
    
    this.markConnected = markConnected;
    return this;
  }

  /**
   * Treat as if a cable is connected
   * @return markConnected
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARK_CONNECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMarkConnected() {
    return markConnected;
  }


  @JsonProperty(value = JSON_PROPERTY_MARK_CONNECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkConnected(@javax.annotation.Nullable Boolean markConnected) {
    this.markConnected = markConnected;
  }

  public PowerFeedRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public PowerFeedRequest tenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    
    this.tenant = tenant;
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TENANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ASNRangeRequestTenant getTenant() {
    return tenant;
  }


  @JsonProperty(value = JSON_PROPERTY_TENANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    this.tenant = tenant;
  }

  public PowerFeedRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ASNRangeRequestOwner getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = owner;
  }

  public PowerFeedRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public PowerFeedRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public PowerFeedRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public PowerFeedRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public PowerFeedRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PowerFeedRequest powerFeedRequest = (PowerFeedRequest) o;
    return Objects.equals(this.powerPanel, powerFeedRequest.powerPanel) &&
        Objects.equals(this.rack, powerFeedRequest.rack) &&
        Objects.equals(this.name, powerFeedRequest.name) &&
        Objects.equals(this.status, powerFeedRequest.status) &&
        Objects.equals(this.type, powerFeedRequest.type) &&
        Objects.equals(this.supply, powerFeedRequest.supply) &&
        Objects.equals(this.phase, powerFeedRequest.phase) &&
        Objects.equals(this.voltage, powerFeedRequest.voltage) &&
        Objects.equals(this.amperage, powerFeedRequest.amperage) &&
        Objects.equals(this.maxUtilization, powerFeedRequest.maxUtilization) &&
        Objects.equals(this.markConnected, powerFeedRequest.markConnected) &&
        Objects.equals(this.description, powerFeedRequest.description) &&
        Objects.equals(this.tenant, powerFeedRequest.tenant) &&
        Objects.equals(this.owner, powerFeedRequest.owner) &&
        Objects.equals(this.comments, powerFeedRequest.comments) &&
        Objects.equals(this.tags, powerFeedRequest.tags) &&
        Objects.equals(this.customFields, powerFeedRequest.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(powerPanel, rack, name, status, type, supply, phase, voltage, amperage, maxUtilization, markConnected, description, tenant, owner, comments, tags, customFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PowerFeedRequest {\n");
    sb.append("    powerPanel: ").append(toIndentedString(powerPanel)).append("\n");
    sb.append("    rack: ").append(toIndentedString(rack)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    supply: ").append(toIndentedString(supply)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    voltage: ").append(toIndentedString(voltage)).append("\n");
    sb.append("    amperage: ").append(toIndentedString(amperage)).append("\n");
    sb.append("    maxUtilization: ").append(toIndentedString(maxUtilization)).append("\n");
    sb.append("    markConnected: ").append(toIndentedString(markConnected)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

