/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.BriefDeviceTypeRequestManufacturer;
import dev.icelabs.netbox.model.NestedTagRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  RackTypeRequest.JSON_PROPERTY_MANUFACTURER,
  RackTypeRequest.JSON_PROPERTY_MODEL,
  RackTypeRequest.JSON_PROPERTY_SLUG,
  RackTypeRequest.JSON_PROPERTY_DESCRIPTION,
  RackTypeRequest.JSON_PROPERTY_FORM_FACTOR,
  RackTypeRequest.JSON_PROPERTY_WIDTH,
  RackTypeRequest.JSON_PROPERTY_U_HEIGHT,
  RackTypeRequest.JSON_PROPERTY_STARTING_UNIT,
  RackTypeRequest.JSON_PROPERTY_DESC_UNITS,
  RackTypeRequest.JSON_PROPERTY_OUTER_WIDTH,
  RackTypeRequest.JSON_PROPERTY_OUTER_HEIGHT,
  RackTypeRequest.JSON_PROPERTY_OUTER_DEPTH,
  RackTypeRequest.JSON_PROPERTY_OUTER_UNIT,
  RackTypeRequest.JSON_PROPERTY_WEIGHT,
  RackTypeRequest.JSON_PROPERTY_MAX_WEIGHT,
  RackTypeRequest.JSON_PROPERTY_WEIGHT_UNIT,
  RackTypeRequest.JSON_PROPERTY_MOUNTING_DEPTH,
  RackTypeRequest.JSON_PROPERTY_OWNER,
  RackTypeRequest.JSON_PROPERTY_COMMENTS,
  RackTypeRequest.JSON_PROPERTY_TAGS,
  RackTypeRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class RackTypeRequest {
  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  @javax.annotation.Nonnull
  private BriefDeviceTypeRequestManufacturer manufacturer;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private String model;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @javax.annotation.Nonnull
  private String slug;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  /**
   * * &#x60;2-post-frame&#x60; - 2-post frame * &#x60;4-post-frame&#x60; - 4-post frame * &#x60;4-post-cabinet&#x60; - 4-post cabinet * &#x60;wall-frame&#x60; - Wall-mounted frame * &#x60;wall-frame-vertical&#x60; - Wall-mounted frame (vertical) * &#x60;wall-cabinet&#x60; - Wall-mounted cabinet * &#x60;wall-cabinet-vertical&#x60; - Wall-mounted cabinet (vertical)
   */
  public enum FormFactorEnum {
    _2_POST_FRAME(String.valueOf("2-post-frame")),
    
    _4_POST_FRAME(String.valueOf("4-post-frame")),
    
    _4_POST_CABINET(String.valueOf("4-post-cabinet")),
    
    WALL_FRAME(String.valueOf("wall-frame")),
    
    WALL_FRAME_VERTICAL(String.valueOf("wall-frame-vertical")),
    
    WALL_CABINET(String.valueOf("wall-cabinet")),
    
    WALL_CABINET_VERTICAL(String.valueOf("wall-cabinet-vertical")),
    
    EMPTY(String.valueOf(""));

    private String value;

    FormFactorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormFactorEnum fromValue(String value) {
      for (FormFactorEnum b : FormFactorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_FORM_FACTOR = "form_factor";
  @javax.annotation.Nullable
  private FormFactorEnum formFactor;

  /**
   * * &#x60;10&#x60; - 10 inches * &#x60;19&#x60; - 19 inches * &#x60;21&#x60; - 21 inches * &#x60;23&#x60; - 23 inches
   */
  public enum WidthEnum {
    NUMBER_10(Integer.valueOf(10)),
    
    NUMBER_19(Integer.valueOf(19)),
    
    NUMBER_21(Integer.valueOf(21)),
    
    NUMBER_23(Integer.valueOf(23));

    private Integer value;

    WidthEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WidthEnum fromValue(Integer value) {
      for (WidthEnum b : WidthEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_WIDTH = "width";
  @javax.annotation.Nullable
  private WidthEnum width;

  public static final String JSON_PROPERTY_U_HEIGHT = "u_height";
  @javax.annotation.Nullable
  private Integer uHeight;

  public static final String JSON_PROPERTY_STARTING_UNIT = "starting_unit";
  @javax.annotation.Nullable
  private Integer startingUnit;

  public static final String JSON_PROPERTY_DESC_UNITS = "desc_units";
  @javax.annotation.Nullable
  private Boolean descUnits;

  public static final String JSON_PROPERTY_OUTER_WIDTH = "outer_width";
  @javax.annotation.Nullable
  private Integer outerWidth;

  public static final String JSON_PROPERTY_OUTER_HEIGHT = "outer_height";
  @javax.annotation.Nullable
  private Integer outerHeight;

  public static final String JSON_PROPERTY_OUTER_DEPTH = "outer_depth";
  @javax.annotation.Nullable
  private Integer outerDepth;

  /**
   * * &#x60;mm&#x60; - Millimeters * &#x60;in&#x60; - Inches
   */
  public enum OuterUnitEnum {
    MM(String.valueOf("mm")),
    
    IN(String.valueOf("in")),
    
    EMPTY(String.valueOf(""));

    private String value;

    OuterUnitEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OuterUnitEnum fromValue(String value) {
      for (OuterUnitEnum b : OuterUnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_OUTER_UNIT = "outer_unit";
  @javax.annotation.Nullable
  private OuterUnitEnum outerUnit;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  @javax.annotation.Nullable
  private Double weight;

  public static final String JSON_PROPERTY_MAX_WEIGHT = "max_weight";
  @javax.annotation.Nullable
  private Integer maxWeight;

  /**
   * * &#x60;kg&#x60; - Kilograms * &#x60;g&#x60; - Grams * &#x60;lb&#x60; - Pounds * &#x60;oz&#x60; - Ounces
   */
  public enum WeightUnitEnum {
    KG(String.valueOf("kg")),
    
    G(String.valueOf("g")),
    
    LB(String.valueOf("lb")),
    
    OZ(String.valueOf("oz")),
    
    EMPTY(String.valueOf(""));

    private String value;

    WeightUnitEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WeightUnitEnum fromValue(String value) {
      for (WeightUnitEnum b : WeightUnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_WEIGHT_UNIT = "weight_unit";
  @javax.annotation.Nullable
  private WeightUnitEnum weightUnit;

  public static final String JSON_PROPERTY_MOUNTING_DEPTH = "mounting_depth";
  @javax.annotation.Nullable
  private Integer mountingDepth;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private ASNRangeRequestOwner owner;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public RackTypeRequest() {
  }

  public RackTypeRequest manufacturer(@javax.annotation.Nonnull BriefDeviceTypeRequestManufacturer manufacturer) {
    
    this.manufacturer = manufacturer;
    return this;
  }

  /**
   * Get manufacturer
   * @return manufacturer
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MANUFACTURER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BriefDeviceTypeRequestManufacturer getManufacturer() {
    return manufacturer;
  }


  @JsonProperty(value = JSON_PROPERTY_MANUFACTURER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setManufacturer(@javax.annotation.Nonnull BriefDeviceTypeRequestManufacturer manufacturer) {
    this.manufacturer = manufacturer;
  }

  public RackTypeRequest model(@javax.annotation.Nonnull String model) {
    
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }

  public RackTypeRequest slug(@javax.annotation.Nonnull String slug) {
    
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlug() {
    return slug;
  }


  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }

  public RackTypeRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public RackTypeRequest formFactor(@javax.annotation.Nullable FormFactorEnum formFactor) {
    
    this.formFactor = formFactor;
    return this;
  }

  /**
   * * &#x60;2-post-frame&#x60; - 2-post frame * &#x60;4-post-frame&#x60; - 4-post frame * &#x60;4-post-cabinet&#x60; - 4-post cabinet * &#x60;wall-frame&#x60; - Wall-mounted frame * &#x60;wall-frame-vertical&#x60; - Wall-mounted frame (vertical) * &#x60;wall-cabinet&#x60; - Wall-mounted cabinet * &#x60;wall-cabinet-vertical&#x60; - Wall-mounted cabinet (vertical)
   * @return formFactor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORM_FACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FormFactorEnum getFormFactor() {
    return formFactor;
  }


  @JsonProperty(value = JSON_PROPERTY_FORM_FACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormFactor(@javax.annotation.Nullable FormFactorEnum formFactor) {
    this.formFactor = formFactor;
  }

  public RackTypeRequest width(@javax.annotation.Nullable WidthEnum width) {
    
    this.width = width;
    return this;
  }

  /**
   * * &#x60;10&#x60; - 10 inches * &#x60;19&#x60; - 19 inches * &#x60;21&#x60; - 21 inches * &#x60;23&#x60; - 23 inches
   * @return width
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WidthEnum getWidth() {
    return width;
  }


  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(@javax.annotation.Nullable WidthEnum width) {
    this.width = width;
  }

  public RackTypeRequest uHeight(@javax.annotation.Nullable Integer uHeight) {
    
    this.uHeight = uHeight;
    return this;
  }

  /**
   * Height in rack units
   * minimum: 1
   * maximum: 100
   * @return uHeight
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_U_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getuHeight() {
    return uHeight;
  }


  @JsonProperty(value = JSON_PROPERTY_U_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setuHeight(@javax.annotation.Nullable Integer uHeight) {
    this.uHeight = uHeight;
  }

  public RackTypeRequest startingUnit(@javax.annotation.Nullable Integer startingUnit) {
    
    this.startingUnit = startingUnit;
    return this;
  }

  /**
   * Starting unit for rack
   * minimum: 1
   * maximum: 32767
   * @return startingUnit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STARTING_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStartingUnit() {
    return startingUnit;
  }


  @JsonProperty(value = JSON_PROPERTY_STARTING_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartingUnit(@javax.annotation.Nullable Integer startingUnit) {
    this.startingUnit = startingUnit;
  }

  public RackTypeRequest descUnits(@javax.annotation.Nullable Boolean descUnits) {
    
    this.descUnits = descUnits;
    return this;
  }

  /**
   * Units are numbered top-to-bottom
   * @return descUnits
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESC_UNITS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDescUnits() {
    return descUnits;
  }


  @JsonProperty(value = JSON_PROPERTY_DESC_UNITS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescUnits(@javax.annotation.Nullable Boolean descUnits) {
    this.descUnits = descUnits;
  }

  public RackTypeRequest outerWidth(@javax.annotation.Nullable Integer outerWidth) {
    
    this.outerWidth = outerWidth;
    return this;
  }

  /**
   * Outer dimension of rack (width)
   * minimum: 0
   * maximum: 32767
   * @return outerWidth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OUTER_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOuterWidth() {
    return outerWidth;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTER_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOuterWidth(@javax.annotation.Nullable Integer outerWidth) {
    this.outerWidth = outerWidth;
  }

  public RackTypeRequest outerHeight(@javax.annotation.Nullable Integer outerHeight) {
    
    this.outerHeight = outerHeight;
    return this;
  }

  /**
   * Outer dimension of rack (height)
   * minimum: 0
   * maximum: 32767
   * @return outerHeight
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OUTER_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOuterHeight() {
    return outerHeight;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTER_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOuterHeight(@javax.annotation.Nullable Integer outerHeight) {
    this.outerHeight = outerHeight;
  }

  public RackTypeRequest outerDepth(@javax.annotation.Nullable Integer outerDepth) {
    
    this.outerDepth = outerDepth;
    return this;
  }

  /**
   * Outer dimension of rack (depth)
   * minimum: 0
   * maximum: 32767
   * @return outerDepth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OUTER_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOuterDepth() {
    return outerDepth;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTER_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOuterDepth(@javax.annotation.Nullable Integer outerDepth) {
    this.outerDepth = outerDepth;
  }

  public RackTypeRequest outerUnit(@javax.annotation.Nullable OuterUnitEnum outerUnit) {
    
    this.outerUnit = outerUnit;
    return this;
  }

  /**
   * * &#x60;mm&#x60; - Millimeters * &#x60;in&#x60; - Inches
   * @return outerUnit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OUTER_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OuterUnitEnum getOuterUnit() {
    return outerUnit;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTER_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOuterUnit(@javax.annotation.Nullable OuterUnitEnum outerUnit) {
    this.outerUnit = outerUnit;
  }

  public RackTypeRequest weight(@javax.annotation.Nullable Double weight) {
    
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * minimum: -1000000
   * maximum: 1000000
   * @return weight
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getWeight() {
    return weight;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(@javax.annotation.Nullable Double weight) {
    this.weight = weight;
  }

  public RackTypeRequest maxWeight(@javax.annotation.Nullable Integer maxWeight) {
    
    this.maxWeight = maxWeight;
    return this;
  }

  /**
   * Maximum load capacity for the rack
   * minimum: 0
   * maximum: 2147483647
   * @return maxWeight
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxWeight() {
    return maxWeight;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_WEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxWeight(@javax.annotation.Nullable Integer maxWeight) {
    this.maxWeight = maxWeight;
  }

  public RackTypeRequest weightUnit(@javax.annotation.Nullable WeightUnitEnum weightUnit) {
    
    this.weightUnit = weightUnit;
    return this;
  }

  /**
   * * &#x60;kg&#x60; - Kilograms * &#x60;g&#x60; - Grams * &#x60;lb&#x60; - Pounds * &#x60;oz&#x60; - Ounces
   * @return weightUnit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEIGHT_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WeightUnitEnum getWeightUnit() {
    return weightUnit;
  }


  @JsonProperty(value = JSON_PROPERTY_WEIGHT_UNIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightUnit(@javax.annotation.Nullable WeightUnitEnum weightUnit) {
    this.weightUnit = weightUnit;
  }

  public RackTypeRequest mountingDepth(@javax.annotation.Nullable Integer mountingDepth) {
    
    this.mountingDepth = mountingDepth;
    return this;
  }

  /**
   * Maximum depth of a mounted device, in millimeters. For four-post racks, this is the distance between the front and rear rails.
   * minimum: 0
   * maximum: 32767
   * @return mountingDepth
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MOUNTING_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMountingDepth() {
    return mountingDepth;
  }


  @JsonProperty(value = JSON_PROPERTY_MOUNTING_DEPTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMountingDepth(@javax.annotation.Nullable Integer mountingDepth) {
    this.mountingDepth = mountingDepth;
  }

  public RackTypeRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ASNRangeRequestOwner getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = owner;
  }

  public RackTypeRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public RackTypeRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public RackTypeRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public RackTypeRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public RackTypeRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RackTypeRequest rackTypeRequest = (RackTypeRequest) o;
    return Objects.equals(this.manufacturer, rackTypeRequest.manufacturer) &&
        Objects.equals(this.model, rackTypeRequest.model) &&
        Objects.equals(this.slug, rackTypeRequest.slug) &&
        Objects.equals(this.description, rackTypeRequest.description) &&
        Objects.equals(this.formFactor, rackTypeRequest.formFactor) &&
        Objects.equals(this.width, rackTypeRequest.width) &&
        Objects.equals(this.uHeight, rackTypeRequest.uHeight) &&
        Objects.equals(this.startingUnit, rackTypeRequest.startingUnit) &&
        Objects.equals(this.descUnits, rackTypeRequest.descUnits) &&
        Objects.equals(this.outerWidth, rackTypeRequest.outerWidth) &&
        Objects.equals(this.outerHeight, rackTypeRequest.outerHeight) &&
        Objects.equals(this.outerDepth, rackTypeRequest.outerDepth) &&
        Objects.equals(this.outerUnit, rackTypeRequest.outerUnit) &&
        Objects.equals(this.weight, rackTypeRequest.weight) &&
        Objects.equals(this.maxWeight, rackTypeRequest.maxWeight) &&
        Objects.equals(this.weightUnit, rackTypeRequest.weightUnit) &&
        Objects.equals(this.mountingDepth, rackTypeRequest.mountingDepth) &&
        Objects.equals(this.owner, rackTypeRequest.owner) &&
        Objects.equals(this.comments, rackTypeRequest.comments) &&
        Objects.equals(this.tags, rackTypeRequest.tags) &&
        Objects.equals(this.customFields, rackTypeRequest.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(manufacturer, model, slug, description, formFactor, width, uHeight, startingUnit, descUnits, outerWidth, outerHeight, outerDepth, outerUnit, weight, maxWeight, weightUnit, mountingDepth, owner, comments, tags, customFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RackTypeRequest {\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    formFactor: ").append(toIndentedString(formFactor)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    uHeight: ").append(toIndentedString(uHeight)).append("\n");
    sb.append("    startingUnit: ").append(toIndentedString(startingUnit)).append("\n");
    sb.append("    descUnits: ").append(toIndentedString(descUnits)).append("\n");
    sb.append("    outerWidth: ").append(toIndentedString(outerWidth)).append("\n");
    sb.append("    outerHeight: ").append(toIndentedString(outerHeight)).append("\n");
    sb.append("    outerDepth: ").append(toIndentedString(outerDepth)).append("\n");
    sb.append("    outerUnit: ").append(toIndentedString(outerUnit)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    maxWeight: ").append(toIndentedString(maxWeight)).append("\n");
    sb.append("    weightUnit: ").append(toIndentedString(weightUnit)).append("\n");
    sb.append("    mountingDepth: ").append(toIndentedString(mountingDepth)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

