/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.BriefIPSecProfile;
import dev.icelabs.netbox.model.BriefOwner;
import dev.icelabs.netbox.model.BriefTenant;
import dev.icelabs.netbox.model.BriefTunnelGroup;
import dev.icelabs.netbox.model.NestedTag;
import dev.icelabs.netbox.model.TunnelEncapsulation;
import dev.icelabs.netbox.model.TunnelStatus;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  Tunnel.JSON_PROPERTY_ID,
  Tunnel.JSON_PROPERTY_URL,
  Tunnel.JSON_PROPERTY_DISPLAY_URL,
  Tunnel.JSON_PROPERTY_DISPLAY,
  Tunnel.JSON_PROPERTY_NAME,
  Tunnel.JSON_PROPERTY_STATUS,
  Tunnel.JSON_PROPERTY_GROUP,
  Tunnel.JSON_PROPERTY_ENCAPSULATION,
  Tunnel.JSON_PROPERTY_IPSEC_PROFILE,
  Tunnel.JSON_PROPERTY_TENANT,
  Tunnel.JSON_PROPERTY_TUNNEL_ID,
  Tunnel.JSON_PROPERTY_DESCRIPTION,
  Tunnel.JSON_PROPERTY_OWNER,
  Tunnel.JSON_PROPERTY_COMMENTS,
  Tunnel.JSON_PROPERTY_TAGS,
  Tunnel.JSON_PROPERTY_CUSTOM_FIELDS,
  Tunnel.JSON_PROPERTY_CREATED,
  Tunnel.JSON_PROPERTY_LAST_UPDATED,
  Tunnel.JSON_PROPERTY_TERMINATIONS_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T09:38:16.451149892Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class Tunnel {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nonnull
  private URI url;

  public static final String JSON_PROPERTY_DISPLAY_URL = "display_url";
  @javax.annotation.Nonnull
  private URI displayUrl;

  public static final String JSON_PROPERTY_DISPLAY = "display";
  @javax.annotation.Nonnull
  private String display;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private TunnelStatus status;

  public static final String JSON_PROPERTY_GROUP = "group";
  @javax.annotation.Nullable
  private JsonNullable<BriefTunnelGroup> group = JsonNullable.<BriefTunnelGroup>undefined();

  public static final String JSON_PROPERTY_ENCAPSULATION = "encapsulation";
  @javax.annotation.Nonnull
  private TunnelEncapsulation encapsulation;

  public static final String JSON_PROPERTY_IPSEC_PROFILE = "ipsec_profile";
  @javax.annotation.Nullable
  private JsonNullable<BriefIPSecProfile> ipsecProfile = JsonNullable.<BriefIPSecProfile>undefined();

  public static final String JSON_PROPERTY_TENANT = "tenant";
  @javax.annotation.Nullable
  private JsonNullable<BriefTenant> tenant = JsonNullable.<BriefTenant>undefined();

  public static final String JSON_PROPERTY_TUNNEL_ID = "tunnel_id";
  @javax.annotation.Nullable
  private JsonNullable<Long> tunnelId = JsonNullable.<Long>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private JsonNullable<BriefOwner> owner = JsonNullable.<BriefOwner>undefined();

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTag> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_TERMINATIONS_COUNT = "terminations_count";
  @javax.annotation.Nonnull
  private Long terminationsCount;

  public Tunnel() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Tunnel(
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_URL) URI url, 
    @JsonProperty(JSON_PROPERTY_DISPLAY_URL) URI displayUrl, 
    @JsonProperty(JSON_PROPERTY_DISPLAY) String display, 
    @JsonProperty(JSON_PROPERTY_CREATED) OffsetDateTime created, 
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED) OffsetDateTime lastUpdated, 
    @JsonProperty(JSON_PROPERTY_TERMINATIONS_COUNT) Long terminationsCount
  ) {
    this();
    this.id = id;
    this.url = url;
    this.displayUrl = displayUrl;
    this.display = display;
    this.created = created;
    this.lastUpdated = lastUpdated;
    this.terminationsCount = terminationsCount;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }



  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getUrl() {
    return url;
  }



  /**
   * Get displayUrl
   * @return displayUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getDisplayUrl() {
    return displayUrl;
  }



  /**
   * Get display
   * @return display
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDisplay() {
    return display;
  }



  public Tunnel name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public Tunnel status(@javax.annotation.Nonnull TunnelStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TunnelStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull TunnelStatus status) {
    this.status = status;
  }

  public Tunnel group(@javax.annotation.Nullable BriefTunnelGroup group) {
    this.group = JsonNullable.<BriefTunnelGroup>of(group);
    
    return this;
  }

  /**
   * Get group
   * @return group
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public BriefTunnelGroup getGroup() {
        return group.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BriefTunnelGroup> getGroup_JsonNullable() {
    return group;
  }
  
  @JsonProperty(JSON_PROPERTY_GROUP)
  public void setGroup_JsonNullable(JsonNullable<BriefTunnelGroup> group) {
    this.group = group;
  }

  public void setGroup(@javax.annotation.Nullable BriefTunnelGroup group) {
    this.group = JsonNullable.<BriefTunnelGroup>of(group);
  }

  public Tunnel encapsulation(@javax.annotation.Nonnull TunnelEncapsulation encapsulation) {
    
    this.encapsulation = encapsulation;
    return this;
  }

  /**
   * Get encapsulation
   * @return encapsulation
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENCAPSULATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TunnelEncapsulation getEncapsulation() {
    return encapsulation;
  }


  @JsonProperty(value = JSON_PROPERTY_ENCAPSULATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEncapsulation(@javax.annotation.Nonnull TunnelEncapsulation encapsulation) {
    this.encapsulation = encapsulation;
  }

  public Tunnel ipsecProfile(@javax.annotation.Nullable BriefIPSecProfile ipsecProfile) {
    this.ipsecProfile = JsonNullable.<BriefIPSecProfile>of(ipsecProfile);
    
    return this;
  }

  /**
   * Get ipsecProfile
   * @return ipsecProfile
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public BriefIPSecProfile getIpsecProfile() {
        return ipsecProfile.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_IPSEC_PROFILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BriefIPSecProfile> getIpsecProfile_JsonNullable() {
    return ipsecProfile;
  }
  
  @JsonProperty(JSON_PROPERTY_IPSEC_PROFILE)
  public void setIpsecProfile_JsonNullable(JsonNullable<BriefIPSecProfile> ipsecProfile) {
    this.ipsecProfile = ipsecProfile;
  }

  public void setIpsecProfile(@javax.annotation.Nullable BriefIPSecProfile ipsecProfile) {
    this.ipsecProfile = JsonNullable.<BriefIPSecProfile>of(ipsecProfile);
  }

  public Tunnel tenant(@javax.annotation.Nullable BriefTenant tenant) {
    this.tenant = JsonNullable.<BriefTenant>of(tenant);
    
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public BriefTenant getTenant() {
        return tenant.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TENANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BriefTenant> getTenant_JsonNullable() {
    return tenant;
  }
  
  @JsonProperty(JSON_PROPERTY_TENANT)
  public void setTenant_JsonNullable(JsonNullable<BriefTenant> tenant) {
    this.tenant = tenant;
  }

  public void setTenant(@javax.annotation.Nullable BriefTenant tenant) {
    this.tenant = JsonNullable.<BriefTenant>of(tenant);
  }

  public Tunnel tunnelId(@javax.annotation.Nullable Long tunnelId) {
    this.tunnelId = JsonNullable.<Long>of(tunnelId);
    
    return this;
  }

  /**
   * Get tunnelId
   * minimum: 0
   * maximum: 9223372036854775807
   * @return tunnelId
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Long getTunnelId() {
        return tunnelId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TUNNEL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Long> getTunnelId_JsonNullable() {
    return tunnelId;
  }
  
  @JsonProperty(JSON_PROPERTY_TUNNEL_ID)
  public void setTunnelId_JsonNullable(JsonNullable<Long> tunnelId) {
    this.tunnelId = tunnelId;
  }

  public void setTunnelId(@javax.annotation.Nullable Long tunnelId) {
    this.tunnelId = JsonNullable.<Long>of(tunnelId);
  }

  public Tunnel description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public Tunnel owner(@javax.annotation.Nullable BriefOwner owner) {
    this.owner = JsonNullable.<BriefOwner>of(owner);
    
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public BriefOwner getOwner() {
        return owner.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BriefOwner> getOwner_JsonNullable() {
    return owner;
  }
  
  @JsonProperty(JSON_PROPERTY_OWNER)
  public void setOwner_JsonNullable(JsonNullable<BriefOwner> owner) {
    this.owner = owner;
  }

  public void setOwner(@javax.annotation.Nullable BriefOwner owner) {
    this.owner = JsonNullable.<BriefOwner>of(owner);
  }

  public Tunnel comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public Tunnel tags(@javax.annotation.Nullable List<NestedTag> tags) {
    
    this.tags = tags;
    return this;
  }

  public Tunnel addTagsItem(NestedTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTag> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTag> tags) {
    this.tags = tags;
  }

  public Tunnel customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public Tunnel putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreated() {
    return created;
  }



  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }



  /**
   * Get terminationsCount
   * @return terminationsCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TERMINATIONS_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTerminationsCount() {
    return terminationsCount;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tunnel tunnel = (Tunnel) o;
    return Objects.equals(this.id, tunnel.id) &&
        Objects.equals(this.url, tunnel.url) &&
        Objects.equals(this.displayUrl, tunnel.displayUrl) &&
        Objects.equals(this.display, tunnel.display) &&
        Objects.equals(this.name, tunnel.name) &&
        Objects.equals(this.status, tunnel.status) &&
        equalsNullable(this.group, tunnel.group) &&
        Objects.equals(this.encapsulation, tunnel.encapsulation) &&
        equalsNullable(this.ipsecProfile, tunnel.ipsecProfile) &&
        equalsNullable(this.tenant, tunnel.tenant) &&
        equalsNullable(this.tunnelId, tunnel.tunnelId) &&
        Objects.equals(this.description, tunnel.description) &&
        equalsNullable(this.owner, tunnel.owner) &&
        Objects.equals(this.comments, tunnel.comments) &&
        Objects.equals(this.tags, tunnel.tags) &&
        Objects.equals(this.customFields, tunnel.customFields) &&
        Objects.equals(this.created, tunnel.created) &&
        Objects.equals(this.lastUpdated, tunnel.lastUpdated) &&
        Objects.equals(this.terminationsCount, tunnel.terminationsCount);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, displayUrl, display, name, status, hashCodeNullable(group), encapsulation, hashCodeNullable(ipsecProfile), hashCodeNullable(tenant), hashCodeNullable(tunnelId), description, hashCodeNullable(owner), comments, tags, customFields, created, lastUpdated, terminationsCount);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tunnel {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    displayUrl: ").append(toIndentedString(displayUrl)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    encapsulation: ").append(toIndentedString(encapsulation)).append("\n");
    sb.append("    ipsecProfile: ").append(toIndentedString(ipsecProfile)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    tunnelId: ").append(toIndentedString(tunnelId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    terminationsCount: ").append(toIndentedString(terminationsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

