/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.BriefOwner;
import dev.icelabs.netbox.model.NestedTag;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from OrganizationalModel.
 */
@JsonPropertyOrder({
  VirtualCircuitType.JSON_PROPERTY_ID,
  VirtualCircuitType.JSON_PROPERTY_URL,
  VirtualCircuitType.JSON_PROPERTY_DISPLAY_URL,
  VirtualCircuitType.JSON_PROPERTY_DISPLAY,
  VirtualCircuitType.JSON_PROPERTY_NAME,
  VirtualCircuitType.JSON_PROPERTY_SLUG,
  VirtualCircuitType.JSON_PROPERTY_COLOR,
  VirtualCircuitType.JSON_PROPERTY_DESCRIPTION,
  VirtualCircuitType.JSON_PROPERTY_OWNER,
  VirtualCircuitType.JSON_PROPERTY_COMMENTS,
  VirtualCircuitType.JSON_PROPERTY_TAGS,
  VirtualCircuitType.JSON_PROPERTY_CUSTOM_FIELDS,
  VirtualCircuitType.JSON_PROPERTY_CREATED,
  VirtualCircuitType.JSON_PROPERTY_LAST_UPDATED,
  VirtualCircuitType.JSON_PROPERTY_VIRTUAL_CIRCUIT_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class VirtualCircuitType {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nonnull
  private URI url;

  public static final String JSON_PROPERTY_DISPLAY_URL = "display_url";
  @javax.annotation.Nonnull
  private URI displayUrl;

  public static final String JSON_PROPERTY_DISPLAY = "display";
  @javax.annotation.Nonnull
  private String display;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @javax.annotation.Nonnull
  private String slug;

  public static final String JSON_PROPERTY_COLOR = "color";
  @javax.annotation.Nullable
  private String color;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private BriefOwner owner;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTag> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_VIRTUAL_CIRCUIT_COUNT = "virtual_circuit_count";
  @javax.annotation.Nonnull
  private Long virtualCircuitCount;

  public VirtualCircuitType() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public VirtualCircuitType(
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_URL) URI url, 
    @JsonProperty(JSON_PROPERTY_DISPLAY_URL) URI displayUrl, 
    @JsonProperty(JSON_PROPERTY_DISPLAY) String display, 
    @JsonProperty(JSON_PROPERTY_CREATED) OffsetDateTime created, 
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED) OffsetDateTime lastUpdated, 
    @JsonProperty(JSON_PROPERTY_VIRTUAL_CIRCUIT_COUNT) Long virtualCircuitCount
  ) {
    this();
    this.id = id;
    this.url = url;
    this.displayUrl = displayUrl;
    this.display = display;
    this.created = created;
    this.lastUpdated = lastUpdated;
    this.virtualCircuitCount = virtualCircuitCount;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }



  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getUrl() {
    return url;
  }



  /**
   * Get displayUrl
   * @return displayUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public URI getDisplayUrl() {
    return displayUrl;
  }



  /**
   * Get display
   * @return display
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDisplay() {
    return display;
  }



  public VirtualCircuitType name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public VirtualCircuitType slug(@javax.annotation.Nonnull String slug) {
    
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlug() {
    return slug;
  }


  @JsonProperty(value = JSON_PROPERTY_SLUG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }

  public VirtualCircuitType color(@javax.annotation.Nullable String color) {
    
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getColor() {
    return color;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(@javax.annotation.Nullable String color) {
    this.color = color;
  }

  public VirtualCircuitType description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public VirtualCircuitType owner(@javax.annotation.Nullable BriefOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BriefOwner getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable BriefOwner owner) {
    this.owner = owner;
  }

  public VirtualCircuitType comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public VirtualCircuitType tags(@javax.annotation.Nullable List<NestedTag> tags) {
    
    this.tags = tags;
    return this;
  }

  public VirtualCircuitType addTagsItem(NestedTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTag> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTag> tags) {
    this.tags = tags;
  }

  public VirtualCircuitType customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public VirtualCircuitType putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreated() {
    return created;
  }



  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }



  /**
   * Get virtualCircuitCount
   * @return virtualCircuitCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VIRTUAL_CIRCUIT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVirtualCircuitCount() {
    return virtualCircuitCount;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualCircuitType virtualCircuitType = (VirtualCircuitType) o;
    return Objects.equals(this.id, virtualCircuitType.id) &&
        Objects.equals(this.url, virtualCircuitType.url) &&
        Objects.equals(this.displayUrl, virtualCircuitType.displayUrl) &&
        Objects.equals(this.display, virtualCircuitType.display) &&
        Objects.equals(this.name, virtualCircuitType.name) &&
        Objects.equals(this.slug, virtualCircuitType.slug) &&
        Objects.equals(this.color, virtualCircuitType.color) &&
        Objects.equals(this.description, virtualCircuitType.description) &&
        Objects.equals(this.owner, virtualCircuitType.owner) &&
        Objects.equals(this.comments, virtualCircuitType.comments) &&
        Objects.equals(this.tags, virtualCircuitType.tags) &&
        Objects.equals(this.customFields, virtualCircuitType.customFields) &&
        Objects.equals(this.created, virtualCircuitType.created) &&
        Objects.equals(this.lastUpdated, virtualCircuitType.lastUpdated) &&
        Objects.equals(this.virtualCircuitCount, virtualCircuitType.virtualCircuitCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, displayUrl, display, name, slug, color, description, owner, comments, tags, customFields, created, lastUpdated, virtualCircuitCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualCircuitType {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    displayUrl: ").append(toIndentedString(displayUrl)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    virtualCircuitCount: ").append(toIndentedString(virtualCircuitCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

