/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.NestedTagRequest;
import dev.icelabs.netbox.model.WritableIKEProposalRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VpnIkeProposalsCreateRequest
 */
@JsonPropertyOrder({
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_NAME,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_DESCRIPTION,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_AUTHENTICATION_METHOD,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_ENCRYPTION_ALGORITHM,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_AUTHENTICATION_ALGORITHM,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_GROUP,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_SA_LIFETIME,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_OWNER,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_COMMENTS,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_TAGS,
  VpnIkeProposalsCreateRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@JsonTypeName("vpn_ike_proposals_create_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class VpnIkeProposalsCreateRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  /**
   * * &#x60;preshared-keys&#x60; - Pre-shared keys * &#x60;certificates&#x60; - Certificates * &#x60;rsa-signatures&#x60; - RSA signatures * &#x60;dsa-signatures&#x60; - DSA signatures
   */
  public enum AuthenticationMethodEnum {
    PRESHARED_KEYS(String.valueOf("preshared-keys")),
    
    CERTIFICATES(String.valueOf("certificates")),
    
    RSA_SIGNATURES(String.valueOf("rsa-signatures")),
    
    DSA_SIGNATURES(String.valueOf("dsa-signatures"));

    private String value;

    AuthenticationMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AuthenticationMethodEnum fromValue(String value) {
      for (AuthenticationMethodEnum b : AuthenticationMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_AUTHENTICATION_METHOD = "authentication_method";
  @javax.annotation.Nonnull
  private AuthenticationMethodEnum authenticationMethod;

  /**
   * * &#x60;aes-128-cbc&#x60; - 128-bit AES (CBC) * &#x60;aes-128-gcm&#x60; - 128-bit AES (GCM) * &#x60;aes-192-cbc&#x60; - 192-bit AES (CBC) * &#x60;aes-192-gcm&#x60; - 192-bit AES (GCM) * &#x60;aes-256-cbc&#x60; - 256-bit AES (CBC) * &#x60;aes-256-gcm&#x60; - 256-bit AES (GCM) * &#x60;3des-cbc&#x60; - 3DES * &#x60;des-cbc&#x60; - DES
   */
  public enum EncryptionAlgorithmEnum {
    AES_128_CBC(String.valueOf("aes-128-cbc")),
    
    AES_128_GCM(String.valueOf("aes-128-gcm")),
    
    AES_192_CBC(String.valueOf("aes-192-cbc")),
    
    AES_192_GCM(String.valueOf("aes-192-gcm")),
    
    AES_256_CBC(String.valueOf("aes-256-cbc")),
    
    AES_256_GCM(String.valueOf("aes-256-gcm")),
    
    _3DES_CBC(String.valueOf("3des-cbc")),
    
    DES_CBC(String.valueOf("des-cbc"));

    private String value;

    EncryptionAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EncryptionAlgorithmEnum fromValue(String value) {
      for (EncryptionAlgorithmEnum b : EncryptionAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENCRYPTION_ALGORITHM = "encryption_algorithm";
  @javax.annotation.Nonnull
  private EncryptionAlgorithmEnum encryptionAlgorithm;

  /**
   * * &#x60;hmac-sha1&#x60; - SHA-1 HMAC * &#x60;hmac-sha256&#x60; - SHA-256 HMAC * &#x60;hmac-sha384&#x60; - SHA-384 HMAC * &#x60;hmac-sha512&#x60; - SHA-512 HMAC * &#x60;hmac-md5&#x60; - MD5 HMAC
   */
  public enum AuthenticationAlgorithmEnum {
    HMAC_SHA1(String.valueOf("hmac-sha1")),
    
    HMAC_SHA256(String.valueOf("hmac-sha256")),
    
    HMAC_SHA384(String.valueOf("hmac-sha384")),
    
    HMAC_SHA512(String.valueOf("hmac-sha512")),
    
    HMAC_MD5(String.valueOf("hmac-md5")),
    
    EMPTY(String.valueOf(""));

    private String value;

    AuthenticationAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AuthenticationAlgorithmEnum fromValue(String value) {
      for (AuthenticationAlgorithmEnum b : AuthenticationAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_AUTHENTICATION_ALGORITHM = "authentication_algorithm";
  @javax.annotation.Nullable
  private AuthenticationAlgorithmEnum authenticationAlgorithm;

  /**
   * Diffie-Hellman group ID  * &#x60;1&#x60; - Group 1 * &#x60;2&#x60; - Group 2 * &#x60;5&#x60; - Group 5 * &#x60;14&#x60; - Group 14 * &#x60;15&#x60; - Group 15 * &#x60;16&#x60; - Group 16 * &#x60;17&#x60; - Group 17 * &#x60;18&#x60; - Group 18 * &#x60;19&#x60; - Group 19 * &#x60;20&#x60; - Group 20 * &#x60;21&#x60; - Group 21 * &#x60;22&#x60; - Group 22 * &#x60;23&#x60; - Group 23 * &#x60;24&#x60; - Group 24 * &#x60;25&#x60; - Group 25 * &#x60;26&#x60; - Group 26 * &#x60;27&#x60; - Group 27 * &#x60;28&#x60; - Group 28 * &#x60;29&#x60; - Group 29 * &#x60;30&#x60; - Group 30 * &#x60;31&#x60; - Group 31 * &#x60;32&#x60; - Group 32 * &#x60;33&#x60; - Group 33 * &#x60;34&#x60; - Group 34
   */
  public enum GroupEnum {
    NUMBER_1(Integer.valueOf(1)),
    
    NUMBER_2(Integer.valueOf(2)),
    
    NUMBER_5(Integer.valueOf(5)),
    
    NUMBER_14(Integer.valueOf(14)),
    
    NUMBER_15(Integer.valueOf(15)),
    
    NUMBER_16(Integer.valueOf(16)),
    
    NUMBER_17(Integer.valueOf(17)),
    
    NUMBER_18(Integer.valueOf(18)),
    
    NUMBER_19(Integer.valueOf(19)),
    
    NUMBER_20(Integer.valueOf(20)),
    
    NUMBER_21(Integer.valueOf(21)),
    
    NUMBER_22(Integer.valueOf(22)),
    
    NUMBER_23(Integer.valueOf(23)),
    
    NUMBER_24(Integer.valueOf(24)),
    
    NUMBER_25(Integer.valueOf(25)),
    
    NUMBER_26(Integer.valueOf(26)),
    
    NUMBER_27(Integer.valueOf(27)),
    
    NUMBER_28(Integer.valueOf(28)),
    
    NUMBER_29(Integer.valueOf(29)),
    
    NUMBER_30(Integer.valueOf(30)),
    
    NUMBER_31(Integer.valueOf(31)),
    
    NUMBER_32(Integer.valueOf(32)),
    
    NUMBER_33(Integer.valueOf(33)),
    
    NUMBER_34(Integer.valueOf(34));

    private Integer value;

    GroupEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GroupEnum fromValue(Integer value) {
      for (GroupEnum b : GroupEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GROUP = "group";
  @javax.annotation.Nonnull
  private GroupEnum group;

  public static final String JSON_PROPERTY_SA_LIFETIME = "sa_lifetime";
  @javax.annotation.Nullable
  private Integer saLifetime;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private ASNRangeRequestOwner owner;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public VpnIkeProposalsCreateRequest() {
  }

  public VpnIkeProposalsCreateRequest name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public VpnIkeProposalsCreateRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public VpnIkeProposalsCreateRequest authenticationMethod(@javax.annotation.Nonnull AuthenticationMethodEnum authenticationMethod) {
    
    this.authenticationMethod = authenticationMethod;
    return this;
  }

  /**
   * * &#x60;preshared-keys&#x60; - Pre-shared keys * &#x60;certificates&#x60; - Certificates * &#x60;rsa-signatures&#x60; - RSA signatures * &#x60;dsa-signatures&#x60; - DSA signatures
   * @return authenticationMethod
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AUTHENTICATION_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AuthenticationMethodEnum getAuthenticationMethod() {
    return authenticationMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHENTICATION_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthenticationMethod(@javax.annotation.Nonnull AuthenticationMethodEnum authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
  }

  public VpnIkeProposalsCreateRequest encryptionAlgorithm(@javax.annotation.Nonnull EncryptionAlgorithmEnum encryptionAlgorithm) {
    
    this.encryptionAlgorithm = encryptionAlgorithm;
    return this;
  }

  /**
   * * &#x60;aes-128-cbc&#x60; - 128-bit AES (CBC) * &#x60;aes-128-gcm&#x60; - 128-bit AES (GCM) * &#x60;aes-192-cbc&#x60; - 192-bit AES (CBC) * &#x60;aes-192-gcm&#x60; - 192-bit AES (GCM) * &#x60;aes-256-cbc&#x60; - 256-bit AES (CBC) * &#x60;aes-256-gcm&#x60; - 256-bit AES (GCM) * &#x60;3des-cbc&#x60; - 3DES * &#x60;des-cbc&#x60; - DES
   * @return encryptionAlgorithm
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ENCRYPTION_ALGORITHM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EncryptionAlgorithmEnum getEncryptionAlgorithm() {
    return encryptionAlgorithm;
  }


  @JsonProperty(value = JSON_PROPERTY_ENCRYPTION_ALGORITHM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEncryptionAlgorithm(@javax.annotation.Nonnull EncryptionAlgorithmEnum encryptionAlgorithm) {
    this.encryptionAlgorithm = encryptionAlgorithm;
  }

  public VpnIkeProposalsCreateRequest authenticationAlgorithm(@javax.annotation.Nullable AuthenticationAlgorithmEnum authenticationAlgorithm) {
    
    this.authenticationAlgorithm = authenticationAlgorithm;
    return this;
  }

  /**
   * * &#x60;hmac-sha1&#x60; - SHA-1 HMAC * &#x60;hmac-sha256&#x60; - SHA-256 HMAC * &#x60;hmac-sha384&#x60; - SHA-384 HMAC * &#x60;hmac-sha512&#x60; - SHA-512 HMAC * &#x60;hmac-md5&#x60; - MD5 HMAC
   * @return authenticationAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTHENTICATION_ALGORITHM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuthenticationAlgorithmEnum getAuthenticationAlgorithm() {
    return authenticationAlgorithm;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHENTICATION_ALGORITHM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthenticationAlgorithm(@javax.annotation.Nullable AuthenticationAlgorithmEnum authenticationAlgorithm) {
    this.authenticationAlgorithm = authenticationAlgorithm;
  }

  public VpnIkeProposalsCreateRequest group(@javax.annotation.Nonnull GroupEnum group) {
    
    this.group = group;
    return this;
  }

  /**
   * Diffie-Hellman group ID  * &#x60;1&#x60; - Group 1 * &#x60;2&#x60; - Group 2 * &#x60;5&#x60; - Group 5 * &#x60;14&#x60; - Group 14 * &#x60;15&#x60; - Group 15 * &#x60;16&#x60; - Group 16 * &#x60;17&#x60; - Group 17 * &#x60;18&#x60; - Group 18 * &#x60;19&#x60; - Group 19 * &#x60;20&#x60; - Group 20 * &#x60;21&#x60; - Group 21 * &#x60;22&#x60; - Group 22 * &#x60;23&#x60; - Group 23 * &#x60;24&#x60; - Group 24 * &#x60;25&#x60; - Group 25 * &#x60;26&#x60; - Group 26 * &#x60;27&#x60; - Group 27 * &#x60;28&#x60; - Group 28 * &#x60;29&#x60; - Group 29 * &#x60;30&#x60; - Group 30 * &#x60;31&#x60; - Group 31 * &#x60;32&#x60; - Group 32 * &#x60;33&#x60; - Group 33 * &#x60;34&#x60; - Group 34
   * minimum: 0
   * maximum: 32767
   * @return group
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_GROUP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GroupEnum getGroup() {
    return group;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGroup(@javax.annotation.Nonnull GroupEnum group) {
    this.group = group;
  }

  public VpnIkeProposalsCreateRequest saLifetime(@javax.annotation.Nullable Integer saLifetime) {
    
    this.saLifetime = saLifetime;
    return this;
  }

  /**
   * Security association lifetime (in seconds)
   * minimum: 0
   * maximum: 2147483647
   * @return saLifetime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SA_LIFETIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSaLifetime() {
    return saLifetime;
  }


  @JsonProperty(value = JSON_PROPERTY_SA_LIFETIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSaLifetime(@javax.annotation.Nullable Integer saLifetime) {
    this.saLifetime = saLifetime;
  }

  public VpnIkeProposalsCreateRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ASNRangeRequestOwner getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = owner;
  }

  public VpnIkeProposalsCreateRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public VpnIkeProposalsCreateRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public VpnIkeProposalsCreateRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public VpnIkeProposalsCreateRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public VpnIkeProposalsCreateRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VpnIkeProposalsCreateRequest vpnIkeProposalsCreateRequest = (VpnIkeProposalsCreateRequest) o;
    return Objects.equals(this.name, vpnIkeProposalsCreateRequest.name) &&
        Objects.equals(this.description, vpnIkeProposalsCreateRequest.description) &&
        Objects.equals(this.authenticationMethod, vpnIkeProposalsCreateRequest.authenticationMethod) &&
        Objects.equals(this.encryptionAlgorithm, vpnIkeProposalsCreateRequest.encryptionAlgorithm) &&
        Objects.equals(this.authenticationAlgorithm, vpnIkeProposalsCreateRequest.authenticationAlgorithm) &&
        Objects.equals(this.group, vpnIkeProposalsCreateRequest.group) &&
        Objects.equals(this.saLifetime, vpnIkeProposalsCreateRequest.saLifetime) &&
        Objects.equals(this.owner, vpnIkeProposalsCreateRequest.owner) &&
        Objects.equals(this.comments, vpnIkeProposalsCreateRequest.comments) &&
        Objects.equals(this.tags, vpnIkeProposalsCreateRequest.tags) &&
        Objects.equals(this.customFields, vpnIkeProposalsCreateRequest.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, authenticationMethod, encryptionAlgorithm, authenticationAlgorithm, group, saLifetime, owner, comments, tags, customFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VpnIkeProposalsCreateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    authenticationMethod: ").append(toIndentedString(authenticationMethod)).append("\n");
    sb.append("    encryptionAlgorithm: ").append(toIndentedString(encryptionAlgorithm)).append("\n");
    sb.append("    authenticationAlgorithm: ").append(toIndentedString(authenticationAlgorithm)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    saLifetime: ").append(toIndentedString(saLifetime)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

