/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.ASNRangeRequestTenant;
import dev.icelabs.netbox.model.IPAddressRequestVrf;
import dev.icelabs.netbox.model.IPRangeRequestRole;
import dev.icelabs.netbox.model.NestedTagRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  WritableIPRangeRequest.JSON_PROPERTY_START_ADDRESS,
  WritableIPRangeRequest.JSON_PROPERTY_END_ADDRESS,
  WritableIPRangeRequest.JSON_PROPERTY_VRF,
  WritableIPRangeRequest.JSON_PROPERTY_TENANT,
  WritableIPRangeRequest.JSON_PROPERTY_STATUS,
  WritableIPRangeRequest.JSON_PROPERTY_ROLE,
  WritableIPRangeRequest.JSON_PROPERTY_DESCRIPTION,
  WritableIPRangeRequest.JSON_PROPERTY_OWNER,
  WritableIPRangeRequest.JSON_PROPERTY_COMMENTS,
  WritableIPRangeRequest.JSON_PROPERTY_TAGS,
  WritableIPRangeRequest.JSON_PROPERTY_CUSTOM_FIELDS,
  WritableIPRangeRequest.JSON_PROPERTY_MARK_POPULATED,
  WritableIPRangeRequest.JSON_PROPERTY_MARK_UTILIZED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T09:38:16.451149892Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WritableIPRangeRequest {
  public static final String JSON_PROPERTY_START_ADDRESS = "start_address";
  @javax.annotation.Nonnull
  private String startAddress;

  public static final String JSON_PROPERTY_END_ADDRESS = "end_address";
  @javax.annotation.Nonnull
  private String endAddress;

  public static final String JSON_PROPERTY_VRF = "vrf";
  @javax.annotation.Nullable
  private JsonNullable<IPAddressRequestVrf> vrf = JsonNullable.<IPAddressRequestVrf>undefined();

  public static final String JSON_PROPERTY_TENANT = "tenant";
  @javax.annotation.Nullable
  private JsonNullable<ASNRangeRequestTenant> tenant = JsonNullable.<ASNRangeRequestTenant>undefined();

  /**
   * Operational status of this range  * &#x60;active&#x60; - Active * &#x60;reserved&#x60; - Reserved * &#x60;deprecated&#x60; - Deprecated
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("active")),
    
    RESERVED(String.valueOf("reserved")),
    
    DEPRECATED(String.valueOf("deprecated"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private JsonNullable<IPRangeRequestRole> role = JsonNullable.<IPRangeRequestRole>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private JsonNullable<ASNRangeRequestOwner> owner = JsonNullable.<ASNRangeRequestOwner>undefined();

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public static final String JSON_PROPERTY_MARK_POPULATED = "mark_populated";
  @javax.annotation.Nullable
  private Boolean markPopulated;

  public static final String JSON_PROPERTY_MARK_UTILIZED = "mark_utilized";
  @javax.annotation.Nullable
  private Boolean markUtilized;

  public WritableIPRangeRequest() {
  }

  public WritableIPRangeRequest startAddress(@javax.annotation.Nonnull String startAddress) {
    
    this.startAddress = startAddress;
    return this;
  }

  /**
   * Get startAddress
   * @return startAddress
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_START_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStartAddress() {
    return startAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_START_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartAddress(@javax.annotation.Nonnull String startAddress) {
    this.startAddress = startAddress;
  }

  public WritableIPRangeRequest endAddress(@javax.annotation.Nonnull String endAddress) {
    
    this.endAddress = endAddress;
    return this;
  }

  /**
   * Get endAddress
   * @return endAddress
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_END_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEndAddress() {
    return endAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_END_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndAddress(@javax.annotation.Nonnull String endAddress) {
    this.endAddress = endAddress;
  }

  public WritableIPRangeRequest vrf(@javax.annotation.Nullable IPAddressRequestVrf vrf) {
    this.vrf = JsonNullable.<IPAddressRequestVrf>of(vrf);
    
    return this;
  }

  /**
   * Get vrf
   * @return vrf
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public IPAddressRequestVrf getVrf() {
        return vrf.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VRF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<IPAddressRequestVrf> getVrf_JsonNullable() {
    return vrf;
  }
  
  @JsonProperty(JSON_PROPERTY_VRF)
  public void setVrf_JsonNullable(JsonNullable<IPAddressRequestVrf> vrf) {
    this.vrf = vrf;
  }

  public void setVrf(@javax.annotation.Nullable IPAddressRequestVrf vrf) {
    this.vrf = JsonNullable.<IPAddressRequestVrf>of(vrf);
  }

  public WritableIPRangeRequest tenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    this.tenant = JsonNullable.<ASNRangeRequestTenant>of(tenant);
    
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ASNRangeRequestTenant getTenant() {
        return tenant.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TENANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ASNRangeRequestTenant> getTenant_JsonNullable() {
    return tenant;
  }
  
  @JsonProperty(JSON_PROPERTY_TENANT)
  public void setTenant_JsonNullable(JsonNullable<ASNRangeRequestTenant> tenant) {
    this.tenant = tenant;
  }

  public void setTenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    this.tenant = JsonNullable.<ASNRangeRequestTenant>of(tenant);
  }

  public WritableIPRangeRequest status(@javax.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Operational status of this range  * &#x60;active&#x60; - Active * &#x60;reserved&#x60; - Reserved * &#x60;deprecated&#x60; - Deprecated
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public WritableIPRangeRequest role(@javax.annotation.Nullable IPRangeRequestRole role) {
    this.role = JsonNullable.<IPRangeRequestRole>of(role);
    
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public IPRangeRequestRole getRole() {
        return role.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<IPRangeRequestRole> getRole_JsonNullable() {
    return role;
  }
  
  @JsonProperty(JSON_PROPERTY_ROLE)
  public void setRole_JsonNullable(JsonNullable<IPRangeRequestRole> role) {
    this.role = role;
  }

  public void setRole(@javax.annotation.Nullable IPRangeRequestRole role) {
    this.role = JsonNullable.<IPRangeRequestRole>of(role);
  }

  public WritableIPRangeRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public WritableIPRangeRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = JsonNullable.<ASNRangeRequestOwner>of(owner);
    
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ASNRangeRequestOwner getOwner() {
        return owner.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ASNRangeRequestOwner> getOwner_JsonNullable() {
    return owner;
  }
  
  @JsonProperty(JSON_PROPERTY_OWNER)
  public void setOwner_JsonNullable(JsonNullable<ASNRangeRequestOwner> owner) {
    this.owner = owner;
  }

  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = JsonNullable.<ASNRangeRequestOwner>of(owner);
  }

  public WritableIPRangeRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public WritableIPRangeRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public WritableIPRangeRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public WritableIPRangeRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public WritableIPRangeRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }

  public WritableIPRangeRequest markPopulated(@javax.annotation.Nullable Boolean markPopulated) {
    
    this.markPopulated = markPopulated;
    return this;
  }

  /**
   * Prevent the creation of IP addresses within this range
   * @return markPopulated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARK_POPULATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMarkPopulated() {
    return markPopulated;
  }


  @JsonProperty(value = JSON_PROPERTY_MARK_POPULATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkPopulated(@javax.annotation.Nullable Boolean markPopulated) {
    this.markPopulated = markPopulated;
  }

  public WritableIPRangeRequest markUtilized(@javax.annotation.Nullable Boolean markUtilized) {
    
    this.markUtilized = markUtilized;
    return this;
  }

  /**
   * Report space as fully utilized
   * @return markUtilized
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MARK_UTILIZED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMarkUtilized() {
    return markUtilized;
  }


  @JsonProperty(value = JSON_PROPERTY_MARK_UTILIZED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkUtilized(@javax.annotation.Nullable Boolean markUtilized) {
    this.markUtilized = markUtilized;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritableIPRangeRequest writableIPRangeRequest = (WritableIPRangeRequest) o;
    return Objects.equals(this.startAddress, writableIPRangeRequest.startAddress) &&
        Objects.equals(this.endAddress, writableIPRangeRequest.endAddress) &&
        equalsNullable(this.vrf, writableIPRangeRequest.vrf) &&
        equalsNullable(this.tenant, writableIPRangeRequest.tenant) &&
        Objects.equals(this.status, writableIPRangeRequest.status) &&
        equalsNullable(this.role, writableIPRangeRequest.role) &&
        Objects.equals(this.description, writableIPRangeRequest.description) &&
        equalsNullable(this.owner, writableIPRangeRequest.owner) &&
        Objects.equals(this.comments, writableIPRangeRequest.comments) &&
        Objects.equals(this.tags, writableIPRangeRequest.tags) &&
        Objects.equals(this.customFields, writableIPRangeRequest.customFields) &&
        Objects.equals(this.markPopulated, writableIPRangeRequest.markPopulated) &&
        Objects.equals(this.markUtilized, writableIPRangeRequest.markUtilized);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(startAddress, endAddress, hashCodeNullable(vrf), hashCodeNullable(tenant), status, hashCodeNullable(role), description, hashCodeNullable(owner), comments, tags, customFields, markPopulated, markUtilized);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritableIPRangeRequest {\n");
    sb.append("    startAddress: ").append(toIndentedString(startAddress)).append("\n");
    sb.append("    endAddress: ").append(toIndentedString(endAddress)).append("\n");
    sb.append("    vrf: ").append(toIndentedString(vrf)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    markPopulated: ").append(toIndentedString(markPopulated)).append("\n");
    sb.append("    markUtilized: ").append(toIndentedString(markUtilized)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

