/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.ASNRangeRequestTenant;
import dev.icelabs.netbox.model.DeviceBayRequestInstalledDevice;
import dev.icelabs.netbox.model.DeviceRoleRequestConfigTemplate;
import dev.icelabs.netbox.model.DeviceTypeRequestDefaultPlatform;
import dev.icelabs.netbox.model.DeviceWithConfigContextRequestCluster;
import dev.icelabs.netbox.model.DeviceWithConfigContextRequestPrimaryIp4;
import dev.icelabs.netbox.model.NestedTagRequest;
import dev.icelabs.netbox.model.PatchedWritableVLANRequestSite;
import dev.icelabs.netbox.model.PatchedWritableVirtualMachineWithConfigContextRequestRole;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Base serializer class for models inheriting from PrimaryModel.
 */
@JsonPropertyOrder({
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_NAME,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_STATUS,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_START_ON_BOOT,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_SITE,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_CLUSTER,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_DEVICE,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_SERIAL,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_ROLE,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_TENANT,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_PLATFORM,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_PRIMARY_IP4,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_PRIMARY_IP6,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_VCPUS,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_MEMORY,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_DISK,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_DESCRIPTION,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_OWNER,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_COMMENTS,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_CONFIG_TEMPLATE,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_LOCAL_CONTEXT_DATA,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_TAGS,
  WritableVirtualMachineWithConfigContextRequest.JSON_PROPERTY_CUSTOM_FIELDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-14T11:30:00.097107667Z[Etc/UTC]", comments = "Generator version: 7.20.0-SNAPSHOT")
public class WritableVirtualMachineWithConfigContextRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  /**
   * * &#x60;offline&#x60; - Offline * &#x60;active&#x60; - Active * &#x60;planned&#x60; - Planned * &#x60;staged&#x60; - Staged * &#x60;failed&#x60; - Failed * &#x60;decommissioning&#x60; - Decommissioning * &#x60;paused&#x60; - Paused
   */
  public enum StatusEnum {
    OFFLINE(String.valueOf("offline")),
    
    ACTIVE(String.valueOf("active")),
    
    PLANNED(String.valueOf("planned")),
    
    STAGED(String.valueOf("staged")),
    
    FAILED(String.valueOf("failed")),
    
    DECOMMISSIONING(String.valueOf("decommissioning")),
    
    PAUSED(String.valueOf("paused"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  /**
   * * &#x60;on&#x60; - On * &#x60;off&#x60; - Off * &#x60;laststate&#x60; - Last State
   */
  public enum StartOnBootEnum {
    ON(String.valueOf("on")),
    
    OFF(String.valueOf("off")),
    
    LASTSTATE(String.valueOf("laststate"));

    private String value;

    StartOnBootEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StartOnBootEnum fromValue(String value) {
      for (StartOnBootEnum b : StartOnBootEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_START_ON_BOOT = "start_on_boot";
  @javax.annotation.Nullable
  private StartOnBootEnum startOnBoot;

  public static final String JSON_PROPERTY_SITE = "site";
  @javax.annotation.Nullable
  private PatchedWritableVLANRequestSite site;

  public static final String JSON_PROPERTY_CLUSTER = "cluster";
  @javax.annotation.Nullable
  private DeviceWithConfigContextRequestCluster cluster;

  public static final String JSON_PROPERTY_DEVICE = "device";
  @javax.annotation.Nullable
  private DeviceBayRequestInstalledDevice device;

  public static final String JSON_PROPERTY_SERIAL = "serial";
  @javax.annotation.Nullable
  private String serial;

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private PatchedWritableVirtualMachineWithConfigContextRequestRole role;

  public static final String JSON_PROPERTY_TENANT = "tenant";
  @javax.annotation.Nullable
  private ASNRangeRequestTenant tenant;

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nullable
  private DeviceTypeRequestDefaultPlatform platform;

  public static final String JSON_PROPERTY_PRIMARY_IP4 = "primary_ip4";
  @javax.annotation.Nullable
  private DeviceWithConfigContextRequestPrimaryIp4 primaryIp4;

  public static final String JSON_PROPERTY_PRIMARY_IP6 = "primary_ip6";
  @javax.annotation.Nullable
  private DeviceWithConfigContextRequestPrimaryIp4 primaryIp6;

  public static final String JSON_PROPERTY_VCPUS = "vcpus";
  @javax.annotation.Nullable
  private Double vcpus;

  public static final String JSON_PROPERTY_MEMORY = "memory";
  @javax.annotation.Nullable
  private Integer memory;

  public static final String JSON_PROPERTY_DISK = "disk";
  @javax.annotation.Nullable
  private Integer disk;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private ASNRangeRequestOwner owner;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  @javax.annotation.Nullable
  private String comments;

  public static final String JSON_PROPERTY_CONFIG_TEMPLATE = "config_template";
  @javax.annotation.Nullable
  private DeviceRoleRequestConfigTemplate configTemplate;

  public static final String JSON_PROPERTY_LOCAL_CONTEXT_DATA = "local_context_data";
  @javax.annotation.Nullable
  private Object localContextData = null;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<NestedTagRequest> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  @javax.annotation.Nullable
  private Map<String, Object> customFields = new HashMap<>();

  public WritableVirtualMachineWithConfigContextRequest() {
  }

  public WritableVirtualMachineWithConfigContextRequest name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public WritableVirtualMachineWithConfigContextRequest status(@javax.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * * &#x60;offline&#x60; - Offline * &#x60;active&#x60; - Active * &#x60;planned&#x60; - Planned * &#x60;staged&#x60; - Staged * &#x60;failed&#x60; - Failed * &#x60;decommissioning&#x60; - Decommissioning * &#x60;paused&#x60; - Paused
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public WritableVirtualMachineWithConfigContextRequest startOnBoot(@javax.annotation.Nullable StartOnBootEnum startOnBoot) {
    
    this.startOnBoot = startOnBoot;
    return this;
  }

  /**
   * * &#x60;on&#x60; - On * &#x60;off&#x60; - Off * &#x60;laststate&#x60; - Last State
   * @return startOnBoot
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_ON_BOOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StartOnBootEnum getStartOnBoot() {
    return startOnBoot;
  }


  @JsonProperty(value = JSON_PROPERTY_START_ON_BOOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartOnBoot(@javax.annotation.Nullable StartOnBootEnum startOnBoot) {
    this.startOnBoot = startOnBoot;
  }

  public WritableVirtualMachineWithConfigContextRequest site(@javax.annotation.Nullable PatchedWritableVLANRequestSite site) {
    
    this.site = site;
    return this;
  }

  /**
   * Get site
   * @return site
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PatchedWritableVLANRequestSite getSite() {
    return site;
  }


  @JsonProperty(value = JSON_PROPERTY_SITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSite(@javax.annotation.Nullable PatchedWritableVLANRequestSite site) {
    this.site = site;
  }

  public WritableVirtualMachineWithConfigContextRequest cluster(@javax.annotation.Nullable DeviceWithConfigContextRequestCluster cluster) {
    
    this.cluster = cluster;
    return this;
  }

  /**
   * Get cluster
   * @return cluster
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLUSTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceWithConfigContextRequestCluster getCluster() {
    return cluster;
  }


  @JsonProperty(value = JSON_PROPERTY_CLUSTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCluster(@javax.annotation.Nullable DeviceWithConfigContextRequestCluster cluster) {
    this.cluster = cluster;
  }

  public WritableVirtualMachineWithConfigContextRequest device(@javax.annotation.Nullable DeviceBayRequestInstalledDevice device) {
    
    this.device = device;
    return this;
  }

  /**
   * Get device
   * @return device
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceBayRequestInstalledDevice getDevice() {
    return device;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevice(@javax.annotation.Nullable DeviceBayRequestInstalledDevice device) {
    this.device = device;
  }

  public WritableVirtualMachineWithConfigContextRequest serial(@javax.annotation.Nullable String serial) {
    
    this.serial = serial;
    return this;
  }

  /**
   * Get serial
   * @return serial
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERIAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSerial() {
    return serial;
  }


  @JsonProperty(value = JSON_PROPERTY_SERIAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSerial(@javax.annotation.Nullable String serial) {
    this.serial = serial;
  }

  public WritableVirtualMachineWithConfigContextRequest role(@javax.annotation.Nullable PatchedWritableVirtualMachineWithConfigContextRequestRole role) {
    
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PatchedWritableVirtualMachineWithConfigContextRequestRole getRole() {
    return role;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(@javax.annotation.Nullable PatchedWritableVirtualMachineWithConfigContextRequestRole role) {
    this.role = role;
  }

  public WritableVirtualMachineWithConfigContextRequest tenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    
    this.tenant = tenant;
    return this;
  }

  /**
   * Get tenant
   * @return tenant
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TENANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ASNRangeRequestTenant getTenant() {
    return tenant;
  }


  @JsonProperty(value = JSON_PROPERTY_TENANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTenant(@javax.annotation.Nullable ASNRangeRequestTenant tenant) {
    this.tenant = tenant;
  }

  public WritableVirtualMachineWithConfigContextRequest platform(@javax.annotation.Nullable DeviceTypeRequestDefaultPlatform platform) {
    
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceTypeRequestDefaultPlatform getPlatform() {
    return platform;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(@javax.annotation.Nullable DeviceTypeRequestDefaultPlatform platform) {
    this.platform = platform;
  }

  public WritableVirtualMachineWithConfigContextRequest primaryIp4(@javax.annotation.Nullable DeviceWithConfigContextRequestPrimaryIp4 primaryIp4) {
    
    this.primaryIp4 = primaryIp4;
    return this;
  }

  /**
   * Get primaryIp4
   * @return primaryIp4
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIMARY_IP4, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceWithConfigContextRequestPrimaryIp4 getPrimaryIp4() {
    return primaryIp4;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIMARY_IP4, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrimaryIp4(@javax.annotation.Nullable DeviceWithConfigContextRequestPrimaryIp4 primaryIp4) {
    this.primaryIp4 = primaryIp4;
  }

  public WritableVirtualMachineWithConfigContextRequest primaryIp6(@javax.annotation.Nullable DeviceWithConfigContextRequestPrimaryIp4 primaryIp6) {
    
    this.primaryIp6 = primaryIp6;
    return this;
  }

  /**
   * Get primaryIp6
   * @return primaryIp6
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIMARY_IP6, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceWithConfigContextRequestPrimaryIp4 getPrimaryIp6() {
    return primaryIp6;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIMARY_IP6, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrimaryIp6(@javax.annotation.Nullable DeviceWithConfigContextRequestPrimaryIp4 primaryIp6) {
    this.primaryIp6 = primaryIp6;
  }

  public WritableVirtualMachineWithConfigContextRequest vcpus(@javax.annotation.Nullable Double vcpus) {
    
    this.vcpus = vcpus;
    return this;
  }

  /**
   * Get vcpus
   * minimum: 0.01
   * maximum: 10000
   * @return vcpus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VCPUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVcpus() {
    return vcpus;
  }


  @JsonProperty(value = JSON_PROPERTY_VCPUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVcpus(@javax.annotation.Nullable Double vcpus) {
    this.vcpus = vcpus;
  }

  public WritableVirtualMachineWithConfigContextRequest memory(@javax.annotation.Nullable Integer memory) {
    
    this.memory = memory;
    return this;
  }

  /**
   * Get memory
   * minimum: 0
   * maximum: 2147483647
   * @return memory
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMemory() {
    return memory;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemory(@javax.annotation.Nullable Integer memory) {
    this.memory = memory;
  }

  public WritableVirtualMachineWithConfigContextRequest disk(@javax.annotation.Nullable Integer disk) {
    
    this.disk = disk;
    return this;
  }

  /**
   * Get disk
   * minimum: 0
   * maximum: 2147483647
   * @return disk
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDisk() {
    return disk;
  }


  @JsonProperty(value = JSON_PROPERTY_DISK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisk(@javax.annotation.Nullable Integer disk) {
    this.disk = disk;
  }

  public WritableVirtualMachineWithConfigContextRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public WritableVirtualMachineWithConfigContextRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ASNRangeRequestOwner getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = owner;
  }

  public WritableVirtualMachineWithConfigContextRequest comments(@javax.annotation.Nullable String comments) {
    
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComments(@javax.annotation.Nullable String comments) {
    this.comments = comments;
  }

  public WritableVirtualMachineWithConfigContextRequest configTemplate(@javax.annotation.Nullable DeviceRoleRequestConfigTemplate configTemplate) {
    
    this.configTemplate = configTemplate;
    return this;
  }

  /**
   * Get configTemplate
   * @return configTemplate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONFIG_TEMPLATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceRoleRequestConfigTemplate getConfigTemplate() {
    return configTemplate;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIG_TEMPLATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigTemplate(@javax.annotation.Nullable DeviceRoleRequestConfigTemplate configTemplate) {
    this.configTemplate = configTemplate;
  }

  public WritableVirtualMachineWithConfigContextRequest localContextData(@javax.annotation.Nullable Object localContextData) {
    
    this.localContextData = localContextData;
    return this;
  }

  /**
   * Local config context data takes precedence over source contexts in the final rendered config context
   * @return localContextData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCAL_CONTEXT_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLocalContextData() {
    return localContextData;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCAL_CONTEXT_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalContextData(@javax.annotation.Nullable Object localContextData) {
    this.localContextData = localContextData;
  }

  public WritableVirtualMachineWithConfigContextRequest tags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    
    this.tags = tags;
    return this;
  }

  public WritableVirtualMachineWithConfigContextRequest addTagsItem(NestedTagRequest tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTagRequest> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@javax.annotation.Nullable List<NestedTagRequest> tags) {
    this.tags = tags;
  }

  public WritableVirtualMachineWithConfigContextRequest customFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public WritableVirtualMachineWithConfigContextRequest putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

  /**
   * Get customFields
   * @return customFields
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getCustomFields() {
    return customFields;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_FIELDS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(@javax.annotation.Nullable Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritableVirtualMachineWithConfigContextRequest writableVirtualMachineWithConfigContextRequest = (WritableVirtualMachineWithConfigContextRequest) o;
    return Objects.equals(this.name, writableVirtualMachineWithConfigContextRequest.name) &&
        Objects.equals(this.status, writableVirtualMachineWithConfigContextRequest.status) &&
        Objects.equals(this.startOnBoot, writableVirtualMachineWithConfigContextRequest.startOnBoot) &&
        Objects.equals(this.site, writableVirtualMachineWithConfigContextRequest.site) &&
        Objects.equals(this.cluster, writableVirtualMachineWithConfigContextRequest.cluster) &&
        Objects.equals(this.device, writableVirtualMachineWithConfigContextRequest.device) &&
        Objects.equals(this.serial, writableVirtualMachineWithConfigContextRequest.serial) &&
        Objects.equals(this.role, writableVirtualMachineWithConfigContextRequest.role) &&
        Objects.equals(this.tenant, writableVirtualMachineWithConfigContextRequest.tenant) &&
        Objects.equals(this.platform, writableVirtualMachineWithConfigContextRequest.platform) &&
        Objects.equals(this.primaryIp4, writableVirtualMachineWithConfigContextRequest.primaryIp4) &&
        Objects.equals(this.primaryIp6, writableVirtualMachineWithConfigContextRequest.primaryIp6) &&
        Objects.equals(this.vcpus, writableVirtualMachineWithConfigContextRequest.vcpus) &&
        Objects.equals(this.memory, writableVirtualMachineWithConfigContextRequest.memory) &&
        Objects.equals(this.disk, writableVirtualMachineWithConfigContextRequest.disk) &&
        Objects.equals(this.description, writableVirtualMachineWithConfigContextRequest.description) &&
        Objects.equals(this.owner, writableVirtualMachineWithConfigContextRequest.owner) &&
        Objects.equals(this.comments, writableVirtualMachineWithConfigContextRequest.comments) &&
        Objects.equals(this.configTemplate, writableVirtualMachineWithConfigContextRequest.configTemplate) &&
        Objects.equals(this.localContextData, writableVirtualMachineWithConfigContextRequest.localContextData) &&
        Objects.equals(this.tags, writableVirtualMachineWithConfigContextRequest.tags) &&
        Objects.equals(this.customFields, writableVirtualMachineWithConfigContextRequest.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, startOnBoot, site, cluster, device, serial, role, tenant, platform, primaryIp4, primaryIp6, vcpus, memory, disk, description, owner, comments, configTemplate, localContextData, tags, customFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritableVirtualMachineWithConfigContextRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startOnBoot: ").append(toIndentedString(startOnBoot)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    primaryIp4: ").append(toIndentedString(primaryIp4)).append("\n");
    sb.append("    primaryIp6: ").append(toIndentedString(primaryIp6)).append("\n");
    sb.append("    vcpus: ").append(toIndentedString(vcpus)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    disk: ").append(toIndentedString(disk)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    configTemplate: ").append(toIndentedString(configTemplate)).append("\n");
    sb.append("    localContextData: ").append(toIndentedString(localContextData)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

