/*
 * NetBox REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.5.2-Docker-4.0.0 (4.5)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.icelabs.netbox.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.icelabs.netbox.model.ASNRangeRequestOwner;
import dev.icelabs.netbox.model.SavedFilterRequest;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * ExtrasSavedFiltersCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0-SNAPSHOT")
public class ExtrasSavedFiltersCreateRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_OBJECT_TYPES = "object_types";
  @SerializedName(SERIALIZED_NAME_OBJECT_TYPES)
  @javax.annotation.Nonnull
  private List<String> objectTypes = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  @javax.annotation.Nonnull
  private String slug;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nullable
  private Integer user;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  @javax.annotation.Nullable
  private Integer weight;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_SHARED = "shared";
  @SerializedName(SERIALIZED_NAME_SHARED)
  @javax.annotation.Nullable
  private Boolean shared;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  @javax.annotation.Nullable
  private Object parameters;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private ASNRangeRequestOwner owner;

  public ExtrasSavedFiltersCreateRequest() {
  }

  public ExtrasSavedFiltersCreateRequest objectTypes(@javax.annotation.Nonnull List<String> objectTypes) {
    
    this.objectTypes = objectTypes;
    return this;
  }

  public ExtrasSavedFiltersCreateRequest addObjectTypesItem(String objectTypesItem) {
    if (this.objectTypes == null) {
      this.objectTypes = new ArrayList<>();
    }
    this.objectTypes.add(objectTypesItem);
    return this;
  }

  /**
   * Get objectTypes
   * @return objectTypes
   */
  @javax.annotation.Nonnull

  public List<String> getObjectTypes() {
    return objectTypes;
  }


  public void setObjectTypes(@javax.annotation.Nonnull List<String> objectTypes) {
    this.objectTypes = objectTypes;
  }

  public ExtrasSavedFiltersCreateRequest name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public ExtrasSavedFiltersCreateRequest slug(@javax.annotation.Nonnull String slug) {
    
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull

  public String getSlug() {
    return slug;
  }


  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }

  public ExtrasSavedFiltersCreateRequest description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public ExtrasSavedFiltersCreateRequest user(@javax.annotation.Nullable Integer user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable

  public Integer getUser() {
    return user;
  }


  public void setUser(@javax.annotation.Nullable Integer user) {
    this.user = user;
  }

  public ExtrasSavedFiltersCreateRequest weight(@javax.annotation.Nullable Integer weight) {
    
    this.weight = weight;
    return this;
  }

  /**
   * Get weight
   * minimum: 0
   * maximum: 32767
   * @return weight
   */
  @javax.annotation.Nullable

  public Integer getWeight() {
    return weight;
  }


  public void setWeight(@javax.annotation.Nullable Integer weight) {
    this.weight = weight;
  }

  public ExtrasSavedFiltersCreateRequest enabled(@javax.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public ExtrasSavedFiltersCreateRequest shared(@javax.annotation.Nullable Boolean shared) {
    
    this.shared = shared;
    return this;
  }

  /**
   * Get shared
   * @return shared
   */
  @javax.annotation.Nullable

  public Boolean getShared() {
    return shared;
  }


  public void setShared(@javax.annotation.Nullable Boolean shared) {
    this.shared = shared;
  }

  public ExtrasSavedFiltersCreateRequest parameters(@javax.annotation.Nullable Object parameters) {
    
    this.parameters = parameters;
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @javax.annotation.Nullable

  public Object getParameters() {
    return parameters;
  }


  public void setParameters(@javax.annotation.Nullable Object parameters) {
    this.parameters = parameters;
  }

  public ExtrasSavedFiltersCreateRequest owner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable

  public ASNRangeRequestOwner getOwner() {
    return owner;
  }


  public void setOwner(@javax.annotation.Nullable ASNRangeRequestOwner owner) {
    this.owner = owner;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtrasSavedFiltersCreateRequest extrasSavedFiltersCreateRequest = (ExtrasSavedFiltersCreateRequest) o;
    return Objects.equals(this.objectTypes, extrasSavedFiltersCreateRequest.objectTypes) &&
        Objects.equals(this.name, extrasSavedFiltersCreateRequest.name) &&
        Objects.equals(this.slug, extrasSavedFiltersCreateRequest.slug) &&
        Objects.equals(this.description, extrasSavedFiltersCreateRequest.description) &&
        Objects.equals(this.user, extrasSavedFiltersCreateRequest.user) &&
        Objects.equals(this.weight, extrasSavedFiltersCreateRequest.weight) &&
        Objects.equals(this.enabled, extrasSavedFiltersCreateRequest.enabled) &&
        Objects.equals(this.shared, extrasSavedFiltersCreateRequest.shared) &&
        Objects.equals(this.parameters, extrasSavedFiltersCreateRequest.parameters) &&
        Objects.equals(this.owner, extrasSavedFiltersCreateRequest.owner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectTypes, name, slug, description, user, weight, enabled, shared, parameters, owner);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtrasSavedFiltersCreateRequest {\n");
    sb.append("    objectTypes: ").append(toIndentedString(objectTypes)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `object_types` to the URL query string
    if (getObjectTypes() != null) {
      for (int i = 0; i < getObjectTypes().size(); i++) {
        try {
          joiner.add(String.format(java.util.Locale.ROOT, "%sobject_types%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getObjectTypes().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `slug` to the URL query string
    if (getSlug() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sslug%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSlug()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `user` to the URL query string
    if (getUser() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%suser%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUser()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `weight` to the URL query string
    if (getWeight() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sweight%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWeight()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%senabled%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEnabled()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shared` to the URL query string
    if (getShared() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sshared%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShared()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `parameters` to the URL query string
    if (getParameters() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sparameters%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getParameters()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(getOwner().toUrlQueryString(prefix + "owner" + suffix));
    }

    return joiner.toString();
  }

  public static class Builder {

    private ExtrasSavedFiltersCreateRequest instance;

    public Builder() {
      this(new ExtrasSavedFiltersCreateRequest());
    }

    protected Builder(ExtrasSavedFiltersCreateRequest instance) {
      this.instance = instance;
    }

    public ExtrasSavedFiltersCreateRequest.Builder objectTypes(List<String> objectTypes) {
      this.instance.objectTypes = objectTypes;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder slug(String slug) {
      this.instance.slug = slug;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder user(Integer user) {
      this.instance.user = user;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder weight(Integer weight) {
      this.instance.weight = weight;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder enabled(Boolean enabled) {
      this.instance.enabled = enabled;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder shared(Boolean shared) {
      this.instance.shared = shared;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder parameters(Object parameters) {
      this.instance.parameters = parameters;
      return this;
    }
    public ExtrasSavedFiltersCreateRequest.Builder owner(ASNRangeRequestOwner owner) {
      this.instance.owner = owner;
      return this;
    }


    /**
    * returns a built ExtrasSavedFiltersCreateRequest instance.
    *
    * The builder is not reusable.
    */
    public ExtrasSavedFiltersCreateRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ExtrasSavedFiltersCreateRequest.Builder builder() {
    return new ExtrasSavedFiltersCreateRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ExtrasSavedFiltersCreateRequest.Builder toBuilder() {
    return new ExtrasSavedFiltersCreateRequest.Builder()
      .objectTypes(getObjectTypes())
      .name(getName())
      .slug(getSlug())
      .description(getDescription())
      .user(getUser())
      .weight(getWeight())
      .enabled(getEnabled())
      .shared(getShared())
      .parameters(getParameters())
      .owner(getOwner());
  }


}

